### ISSUE TITLE
Sharepoint Online issue while applying Search Settings to a site

### ISSUE THREAD

**Issue by rathnamvemula** [SharePoint/PnP-Sites-Core#1056]
#### Category
[ ] Bug

#### Environment
[ ] Office 365 / SharePoint Online

I am facing the issue while applying search settings to during provisioning a site. It does not happen all the times. 
Steps to Reproduce:
I provisioned two sites (with few minutes difference). One of the site created successfully and other site is facing the issue while applying search settings. From the logs I can see there is only 15 seconds difference between two sites while applying the Search Settings. Not sure whether the first site is processing the search settings during which second site tried to access it and got the error.

The issue is 
`at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at Microsoft.SharePoint.Client.SearchExtensions.SetSearchConfigurationImplementation(ClientRuntimeContext context, SearchObjectLevel searchObjectLevel, String searchConfiguration)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectSearchSettings.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo)
   at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)
`

.

**Comment by jansenbe** [comment]
Hi @rathnamvemula ,

This might be due a temporary, short, issue in the service. Can you reproduce this behavior?

**Comment by rathnamvemula** [comment]
Hi jansenbe,
The issue is intermittent. It happens sometimes only. Is there a chance if I provision two sites at similar time, and both sites are trying to access the Search Settings from the xml at the same time, this kind of issue occurs?

**Comment by jansenbe** [comment]
Reading the same file at the same time should not cause any issues. I would recommend trying to get more information (e.g. detailed error message, correlationid,...). I'll close this issue now, but feel free to re-open when you've more details.
