### ISSUE TITLE
Cannot invoke method or retrieve property from null object. Object returned by the following call stack is null. "GetCatalog"

### ISSUE THREAD

**Issue by Bhavesha** [SharePoint/PnP-Sites-Core#1248]
Hello,

I am facing an issue while exporting template for SharePoint 2013 Publishing Site Collection. Issue occurs when the framework tries to get page content. It progresses successfully to retrieve 9 properties out of 15 and fails when trying to get Page Contents as mentioned below. 
01/15 - Regional Settings
02/15 - Supported UI Languages
03/15 - Audit Settings
04/15 - Site Security
05/15 - Fields
06/15 - Content Types
07/15 - List instances
08/15 - Features
09/15 - Composed Looks

The error is, Cannot invoke method or retrieve property from null object. Object returned by the following call stack is null. "GetCatalog"
at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)   at Microsoft.SharePoint.Client.BrandingExtensions.GetComposedLook(Web web, String composedLookName)   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectComposedLook.DetectComposedLook(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo, PnPMonitoredScope scope, SharePointConnector spConnector, SharePointConnector spConnectorRoot)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectComposedLook.ExtractObjects(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo).

Can you please help to resolve this issue.

Thanks.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
