### ISSUE TITLE
DeployMasterPage fails on SP 2013: Column 'Title' does not exist.

### ISSUE THREAD

**Issue by BitSchupser** [SharePoint/PnP-Sites-Core#1307]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 15.0.4945.1000

#### Expected or Desired Behavior
When I call `"web.DeployMasterPage(@"Masterpages\seattle.master", "Seattle", "Seattle Masterpage");` the Masterpage "seattle.master" located in my solution will be provisioned.

#### Observed Behavior
ServerException, stating the the column 'Title' does not exist.:

```
Microsoft.SharePoint.Client.ServerException occurred
  HResult=0x80131500
  Message=Column 'Title' does not exist. It may have been deleted by another user.  /sites/TEST1/ITalkCalendar/italk-calendar-develop/_catalogs/masterpage
  Source=Microsoft.SharePoint.Client.Runtime
  StackTrace:
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay) in C:\Users\arrampp\Source\Repos\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\ClientContextExtensions.cs:line 93
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay) in C:\Users\arrampp\Source\Repos\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\ClientContextExtensions.cs:line 48
   at Microsoft.SharePoint.Client.BrandingExtensions.DeployMasterPage(Web web, String sourceFilePath, String title, String description, String uiVersion, String defaultCSSFile, String folderPath) in C:\Users\arrampp\Source\Repos\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\BrandingExtensions.cs:line 577
   at CSProvisioning.Migrations.M002AddParticipantsOfToEvent.DeployJavascriptLibraries(Web web) in C:\Users\arrampp\Projekte\education\sharepoint-italk-calendar\CSProvisioning\CSProvisioning\Migrations\M002AddParticipantsOfToEvent.cs:line 24
   at CSProvisioning.Migrations.M002AddParticipantsOfToEvent.Execute(Web toMigrate) in C:\Users\arrampp\Projekte\education\sharepoint-italk-calendar\CSProvisioning\CSProvisioning\Migrations\M002AddParticipantsOfToEvent.cs:line 17
   at SharePointMigrator.Runtime.MigrationRunner.Execute(IMigration migration) in C:\Users\arrampp\Projekte\education\sharepoint-italk-calendar\CSProvisioning\sharepointmigrator\SharePointMigrator.Runner\MigrationRunner.cs:line 39
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at SharePointMigrator.Runtime.MigrationRunner.Run() in C:\Users\arrampp\Projekte\education\sharepoint-italk-calendar\CSProvisioning\sharepointmigrator\SharePointMigrator.Runner\MigrationRunner.cs:line 30
   at CSProvisioning.Program.Main(String[] args) in C:\Users\arrampp\Projekte\education\sharepoint-italk-calendar\CSProvisioning\CSProvisioning\Program.cs:line 22
```

#### Steps to Reproduce
Deploy a master page to SharePoint 2013 on Premise.

#### Hints
When I comment the line `listItem["Title"] = title;` in `BrandingExtensions.DeployMasterPage(...)`, the exception does not occur.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
