### ISSUE TITLE
Error in PageExtensions.GetWebPartXml issued by change in PagesSerializer when filling the WebPart.Contents

### ISSUE THREAD

**Issue by gszdev** [SharePoint/PnP-Sites-Core#1399]
Error creating a template file (*.pnp).
I tested it with PowerShell and a console app.
This leads me to the following change:
see commit 
 Fixed PagesSerializer to fix issue with test XMLSerializer_Deserialize_Pages_201605
[](https://github.com/SharePoint/PnP-Sites-Core/commit/983b155f9f6a5f52761b758e376204fb61277e7a#diff-ba4777e00a769341fe2c13c4f7a9e1fd)

**Which PnP repository should you use to report the issue?** 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Bug free tempalte file creating.

#### Observed Behavior

When creating the tempalte using Get-PnpProvisioningTemplate the following exception occurs:

$error[0].Exception.Stacktrace
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.SharePoint.Client.**PageExtensions.GetWebPartXml**(Web web, Guid webPartId, String serverRelativePageUrl)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectPageContents.ExtractObjects(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
   at SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate.ExtractTemplate(XMLPnPSchemaVersion schema, String path, String packageName)
   at SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate.ExecuteCmdlet()
   at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()

see commit 
 Fixed PagesSerializer to fix issue with test XMLSerializer_Deserialize_Pages_201605
[](https://github.com/SharePoint/PnP-Sites-Core/commit/983b155f9f6a5f52761b758e376204fb61277e7a#diff-ba4777e00a769341fe2c13c4f7a9e1fd)

#### Steps to Reproduce

- Create two new empty Team Sites using STS#0 as tempalte
- Get the PnpPfovistioning Template
     Get-Module SharePointPnPPowerShellOnline* -ListAvailable | Select-Object Name,Version | Sort-Object Version -Descendin

     $pnpFile = "C:\Temp\PnP-Provisioning-File_TestSite.pnp"

     Set-PnPTraceLog -On -Level Debug
     Get-PnpProvisioningTemplate -Out $pnpFile -Debug

**Comment by gszdev** [comment]
Fixed with version 2.19.1710.1
