### ISSUE TITLE
NullReferenceException at CryptographyHelper.GetCryptoProviderForSha256 when using dotnet 4.7

### ISSUE THREAD

**Issue by baywet** [SharePoint/PnP-Sites-Core#1405]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

PnP Sites core version used 2.19.1710.0
If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Certificate authentication to work properly with .net 4.7.

#### Observed Behavior
We're using PnP Sites Core to acquire a clientContext using a certificate in an app only flow with code looking like that.
```
authManager.GetAzureADAppOnlyAuthenticatedContext(siteUrl, Settings.AzureAdWebApiAppId, Settings.AzureTenant, CertificateProvider.AppCertificate);
```
After upgrading to .net 4.7 (changing the project target) we got the following exception
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.IdentityModel.Clients.ActiveDirectory.CryptographyHelper.GetCryptoProviderForSha256(RSACryptoServiceProvider rsaProvider)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.CryptographyHelper.SignWithCertificate(String message, X509Certificate2 x509Certificate)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.JsonWebToken.Sign(ClientAssertionCertificate credential)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.RequestParameters.AddClientKey(ClientKey clientKey)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__0.MoveNext()
vstest.executionengine.x86.exe Error: 0 : 10/16/2017 10:10:50: bbc2450e-ea39-415f-b8c4-1b6273ef9d75 - <RunAsync>d__0: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.IdentityModel.Clients.ActiveDirectory.CryptographyHelper.GetCryptoProviderForSha256(RSACryptoServiceProvider rsaProvider)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.CryptographyHelper.SignWithCertificate(String message, X509Certificate2 x509Certificate)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.JsonWebToken.Sign(ClientAssertionCertificate credential)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.RequestParameters.AddClientKey(ClientKey clientKey)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__0.MoveNext()
Exception thrown: 'System.NullReferenceException' in Microsoft.IdentityModel.Clients.ActiveDirectory.dll
```
Note: the issue is actually located in ADAL.net but it's already been fixed. See this https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/752
(other potentially related issue https://github.com/Azure/azure-sdk-for-net/issues/3521)

#### Steps to Reproduce
Create a .net 4.7 project.
Register an application in AAD with a certificate credential.
Implement the above code to get a client context.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
