### ISSUE TITLE
MissingMethodException when upgrading from ADAL 2.X to MSAL 3.X

### ISSUE THREAD

**Issue by baywet** [SharePoint/PnP-Sites-Core#1407]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

PnP Version 2.19.1710.0

#### Expected or Desired Behavior
ADAL to be upgraded to MSAL and properly implemented in PnP-Sites-Core.

#### Observed Behavior
Related to this issue https://github.com/SharePoint/PnP-Sites-Core/issues/1405
After seeing that it's been fixed in MSAL, I decided to upgrade the dependency on my end.
That resulted in that exception
```
Result StackTrace:	
at OfficeDevPnP.Core.AuthenticationManager.<>c__DisplayClass36_0.<GetAzureADAppOnlyAuthenticatedContext>b__0(Object sender, WebRequestEventArgs args)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.OnExecutingWebRequest(WebRequestEventArgs args)
   at Microsoft.SharePoint.Client.ClientContext.GetFormDigestInfoPrivate()
   at Microsoft.SharePoint.Client.ClientContext.EnsureFormDigest()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at MeetingWorkspace.Tests.testHelper.<ClearPreviousPages>d__2.MoveNext() in \testHelper.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MeetingWorkspace.Tests.MeetingSeriesUnitTest.<AddAttendeeToInstanceOfSeries>d__12.MoveNext() in \MeetingSeriesUnitTest.cs:line 262
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)
Result Message:	
Test method MeetingWorkspace.Tests.MeetingSeriesUnitTest.AddAttendeeToInstanceOfSeries threw exception: 
System.MissingMethodException: Method not found: 'Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationResult Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireToken(System.String, Microsoft.IdentityModel.Clients.ActiveDirectory.ClientAssertionCertificate)'.
```
That's because they changed the exposed methods, It's now AcquireTokenAsync which should be implemented instead.

#### Steps to Reproduce
Create a .net project (I don't think targeted version matters much but I'm using 4.7 at the time)
Implement the code to get a app only client context from a client certificate. (see details in other bug)
Upgrade to MSAL latest

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
