### ISSUE TITLE
Get-PnPProvisioningTemplate : One or more errors occurred

### ISSUE THREAD

**Issue by haavardmeling** [SharePoint/PnP-Sites-Core#1411]
#### Category
[ x] Bug
[ ] Enhancement

#### Environment
[ x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Exported template

#### Observed Behavior
Error message when running Get-PnPProvisioningTemplate : One or more errors occurred.

Stacktrace:
`$test[0].Exception.StackTrace
   at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ExtractWebhooks(List siteList, ListInst
ance list)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ExtractObjects(Web web, ProvisioningTem
plate template, ProvisioningTemplateCreationInformation creationInfo)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, Provis
ioningTemplateCreationInformation creationInfo)
   at SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate.ExtractTemplate(XMLPnPSchemaVersion schema,
 String path, String packageName)
   at SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate.ExecuteCmdlet()
   at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()`
#### Steps to Reproduce
Version is 2.19.1710.1
Connect-PnPOnline –Url https://xxx.sharepoint.com/sites/MyNewTestTeamSite -UseWebLogin
Get-PnPProvisioningTemplate -Out C:\Temp\testing2.pnp -ErrorVariable test

**Comment by erwinvanhunen** [comment]
Thank you for reporting this. after testing it myself I can confirm this to be an issue. We will look into it.

**Comment by erwinvanhunen** [comment]
We found the issue and a fix has been merged in the dev branch through PR #1412. I will close this issue for now, but do not hesitate to re-open if the issue still occurs. The fix will be made available in the next release of the Core Library/PowerShell.
