### ISSUE TITLE
Site Security Provisioning: Slow performance and 401 Error

### ISSUE THREAD

**Issue by MattPPMConsultant** [SharePoint/PnP-Sites-Core#1516]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Robust and timely application of the pnp:Security template elements. 

#### Observed Behaviour
We are working with Project sites in a Project Online site collection.
We have a Project site template where we are creating 3x custom groups to be used in the site. The inheritance is broken and the 3 groups created with security levels as defined at the site collection.
```
<pnp:Security BreakRoleInheritance="true" CopyRoleAssignments="false" ClearSubscopes="true">
				<pnp:SiteGroups>
					<pnp:SiteGroup Title="{siteid} - CH Project Managers" Description="" Owner="{associatedownergroup}" AllowMembersEditMembership="false" AllowRequestToJoinLeave="false" AutoAcceptRequestToJoinLeave="false" OnlyAllowMembersViewMembership="false"/>
					<pnp:SiteGroup Title="{siteid} - CH Finance Users" Description="" Owner="{associatedownergroup}" AllowMembersEditMembership="true" AllowRequestToJoinLeave="false" AutoAcceptRequestToJoinLeave="false" OnlyAllowMembersViewMembership="true"/>
					<pnp:SiteGroup Title="{siteid} - CH-Core Team" Description="" Owner="{associatedownergroup}" AllowMembersEditMembership="false" AllowRequestToJoinLeave="false" AutoAcceptRequestToJoinLeave="false" OnlyAllowMembersViewMembership="true"/>
				</pnp:SiteGroups>
				<pnp:Permissions>
					<pnp:RoleAssignments>
						<pnp:RoleAssignment Principal="{siteid} - CH Finance Users" RoleDefinition="PS Finance" />
						<pnp:RoleAssignment Principal="{siteid} - CH Project Managers" RoleDefinition="PS Project Manger" />
						<pnp:RoleAssignment Principal="{siteid} - CH-Core Team" RoleDefinition="PS Core Team" />
					</pnp:RoleAssignments>
				</pnp:Permissions>
			</pnp:Security>

```
When applying the template via POSH it takes circa 32 minutes to apply. (This is not deemed to be performant and causes a huge issue when trying to provision sites in bulk eg 800 sites as part of a migration)

Powershell log:
```
powershell.exe Information: 0 : 2018-01-02 13:13:32.0072	[OfficeDevPnP.Core]	[0]	[Information]	File Remotetemplate.xml retrieved from folder 	0ms	
powershell.exe Information: 0 : 2018-01-02 13:13:32.0097	[OfficeDevPnP.Core]	[0]	[Information]	File Remotetemplate.xml retrieved from folder 	0ms	
powershell.exe Information: 0 : 2018-01-02 13:13:33.0847	[Provisioning]	[10]	[Debug]	Code execution scope started	0ms	ba6a254b-10c0-4c4a-8ee9-95a9362ec877
powershell.exe Information: 0 : 2018-01-02 13:13:33.0857	[Provisioning]	[10]	[Information]	ProgressDelegate registered	1ms	ba6a254b-10c0-4c4a-8ee9-95a9362ec877
powershell.exe Information: 0 : 2018-01-02 13:13:33.0865	[Provisioning]	[10]	[Information]	MessagesDelegate registered	2ms	ba6a254b-10c0-4c4a-8ee9-95a9362ec877
powershell.exe Information: 0 : 2018-01-02 13:13:52.7329	[Extensibility Providers]	[10]	[Debug]	Code execution scope started	9ms	ba6a254b-10c0-4c4a-8ee9-95a9362ec877
powershell.exe Information: 0 : 2018-01-02 13:13:52.7339	[Extensibility Providers]	[10]	[Debug]	Code execution scope ended	10ms	ba6a254b-10c0-4c4a-8ee9-95a9362ec877
powershell.exe Information: 0 : 2018-01-02 13:13:53.0659	[Site Security]	[10]	[Debug]	Code execution scope started	0ms	ba6a254b-10c0-4c4a-8ee9-95a9362ec877
powershell.exe Information: 0 : 2018-01-02 13:46:39.7369	[Site Security]	[10]	[Debug]	Code execution scope ended	1966660ms	ba6a254b-10c0-4c4a-8ee9-95a9362ec877
powershell.exe Information: 0 : 2018-01-02 13:46:39.7779	[List instances]	[10]	[Debug]	Code execution scope started	0ms	ba6a254b-10c0-4c4a-8ee9-95a9362ec877
powershell.exe Information: 0 : 2018-01-02 13:46:44.7765	[List instances]	[10]	[Debug]	Updating list Forecast Region Sales	4998ms	ba6a254b-10c0-4c4a-8ee9-95a9362ec877
powershell.exe Information: 0 : 2018-01-02 13:46:53.4712	[List instances]	[10]	[Debug]	Updating list Market Sales	13693ms	ba6a254b-10c0-4c4a-8ee9-95a9362ec877
powershell.exe Information: 0 : 2018-01-02 13:47:01.7437	[List instances]	[10]	[Debug]	Updating list In Scope Finance Markets	21965ms	ba6a254b-10c0-4c4a-8ee9-95a9362ec877
powershell.exe Information: 0 : 2018-01-02 13:47:09.7938	[List instances]	[10]	[Debug]	Code execution scope ended	30015ms	ba6a254b-10c0-4c4a-8ee9-95a9362ec877
powershell.exe Information: 0 : 2018-01-02 13:47:09.7948	[Lookup Fields]	[10]	[Debug]	Code execution scope started	0ms	ba6a254b-10c0-4c4a-8ee9-95a9362ec877
powershell.exe Information: 0 : 2018-01-02 13:47:24.8320	[Lookup Fields]	[10]	[Debug]	Code execution scope ended	15037ms	ba6a254b-10c0-4c4a-8ee9-95a9362ec877
powershell.exe Information: 0 : 2018-01-02 13:47:24.8407	[Persist Template Info]	[10]	[Debug]	Code execution scope started	0ms	ba6a254b-10c0-4c4a-8ee9-95a9362ec877
powershell.exe Information: 0 : 2018-01-02 13:47:26.8458	[Persist Template Info]	[10]	[Debug]	Code execution scope ended	2005ms	ba6a254b-10c0-4c4a-8ee9-95a9362ec877
powershell.exe Information: 0 : 2018-01-02 13:47:26.8465	[Provisioning]	[10]	[Debug]	Code execution scope ended	2033752ms	ba6a254b-10c0-4c4a-8ee9-95a9362ec877
```
When using the template with our provisioning engine set to concurrently apply the template 6 sites, we often find that we are getting 'The remote server   returned an error: (401) Unauthorized.'  As a result the site fails to provision.

```
{"ExceptionMessage":"The   remote server returned an error: (401)   Unauthorized.","SiteCollection":"/sites/PWA-CH_DEV-Fusion/","Url":"z_BulkProvisioningTest   260","ExceptionStackTrace":"at   System.Net.HttpWebRequest.GetResponse()\r\n     at Microsoft.SharePoint.Client.SPWebRequestExecutor.Execute()\r\n   at   Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder   sb)\r\n   at   Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()\r\n   at   Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()\r\n   at   Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()\r\n   at   Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext   clientContext, Int32 retryCount, Int32 delay)\r\n   at   Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext   clientContext, Int32 retryCount, Int32 delay)\r\n   at   Microsoft.SharePoint.Client.ClientObjectExtensions.EnsureProperty[T,TResult](T   clientObject, Expression`1 propertySelector)\r\n   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectSiteSecurity.GetPrincipal(Web   web, TokenParser parser, PnPMonitoredScope scope, IEnumerable`1 groups,   RoleAssignment roleAssignment)\r\n   at   OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectSiteSecurity.ProvisionObjects(Web   web, ProvisioningTemplate template, TokenParser parser,   ProvisioningTemplateApplyingInformation applyingInformation)\r\n   at   OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web   web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation   provisioningInfo)\r\n   at   Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web,   ProvisioningTemplate template, ProvisioningTemplateApplyingInformation   applyingInformation)\r\n   at   PartnerName.SharePointOnline.RemoteProvisioning.ApplyJob.Functions.ProcessQueueMessageInner(TemplateRequest   templateRequest, TextWriter log) in   C:\\src\\PartnerName.ClientName.RemoteProvisioning\\PartnerName.SharePointOnline.RemoteProvisioning.ApplyJob\\Functions.cs:line   105\r\n   at   PartnerName.SharePointOnline.RemoteProvisioning.ApplyJob.Functions.ProcessQueueMessage(AzureQueueMessage   message, TextWriter log) in   C:\\src\\PartnerName.ClientName.RemoteProvisioning\\PartnerName.SharePointOnline.RemoteProvisioning.ApplyJob\\Functions.cs:line   133"}
```
#### Steps to Reproduce
To Repro this, first create the security levels at the SC level:

```
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2016/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.14.1704.0, Culture=neutral, PublicKeyToken=3751622786b357c2" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-D1F1F6CA4D0F4A7BB350F055D7C2CBF3">
    <pnp:ProvisioningTemplate ID="TEMPLATE-D1F1F6CA4D0F4A7BB350F055D7C2CBF3" Version="1" BaseSiteTemplate="PWA#0">
      <pnp:Security>
        <pnp:Permissions>
          <pnp:RoleDefinitions>
            <pnp:RoleDefinition Name="View Only" Description="Can view pages, list items, and documents. Document types with server-side file handlers can be viewed in the browser but not downloaded.">
              <pnp:Permissions>
                <pnp:Permission>EmptyMask</pnp:Permission>
                <pnp:Permission>ViewListItems</pnp:Permission>
                <pnp:Permission>ViewVersions</pnp:Permission>
                <pnp:Permission>ViewFormPages</pnp:Permission>
                <pnp:Permission>Open</pnp:Permission>
                <pnp:Permission>ViewPages</pnp:Permission>
                <pnp:Permission>CreateSSCSite</pnp:Permission>
                <pnp:Permission>BrowseUserInfo</pnp:Permission>
                <pnp:Permission>UseClientIntegration</pnp:Permission>
                <pnp:Permission>UseRemoteAPIs</pnp:Permission>
                <pnp:Permission>CreateAlerts</pnp:Permission>
              </pnp:Permissions>
            </pnp:RoleDefinition>
            <pnp:RoleDefinition Name="Manage Subsites" Description="Grants the permission to manage subsites.">
              <pnp:Permissions>
                <pnp:Permission>EmptyMask</pnp:Permission>
                <pnp:Permission>ManageSubwebs</pnp:Permission>
              </pnp:Permissions>
            </pnp:RoleDefinition>
            <pnp:RoleDefinition Name="Web Administrators (Microsoft Project Web App)" Description="Users who have Manage Microsoft SharePoint Foundation permission in Microsoft Project Web App.">
              <pnp:Permissions>
                <pnp:Permission>EmptyMask</pnp:Permission>
                <pnp:Permission>ViewListItems</pnp:Permission>
                <pnp:Permission>AddListItems</pnp:Permission>
                <pnp:Permission>EditListItems</pnp:Permission>
                <pnp:Permission>DeleteListItems</pnp:Permission>
                <pnp:Permission>ApproveItems</pnp:Permission>
                <pnp:Permission>OpenItems</pnp:Permission>
                <pnp:Permission>ViewVersions</pnp:Permission>
                <pnp:Permission>DeleteVersions</pnp:Permission>
                <pnp:Permission>CancelCheckout</pnp:Permission>
                <pnp:Permission>ManagePersonalViews</pnp:Permission>
                <pnp:Permission>ManageLists</pnp:Permission>
                <pnp:Permission>ViewFormPages</pnp:Permission>
                <pnp:Permission>AnonymousSearchAccessList</pnp:Permission>
                <pnp:Permission>Open</pnp:Permission>
                <pnp:Permission>ViewPages</pnp:Permission>
                <pnp:Permission>AddAndCustomizePages</pnp:Permission>
                <pnp:Permission>ApplyThemeAndBorder</pnp:Permission>
                <pnp:Permission>ApplyStyleSheets</pnp:Permission>
                <pnp:Permission>ViewUsageData</pnp:Permission>
                <pnp:Permission>CreateSSCSite</pnp:Permission>
                <pnp:Permission>ManageSubwebs</pnp:Permission>
                <pnp:Permission>CreateGroups</pnp:Permission>
                <pnp:Permission>ManagePermissions</pnp:Permission>
                <pnp:Permission>BrowseDirectories</pnp:Permission>
                <pnp:Permission>BrowseUserInfo</pnp:Permission>
                <pnp:Permission>AddDelPrivateWebParts</pnp:Permission>
                <pnp:Permission>UpdatePersonalWebParts</pnp:Permission>
                <pnp:Permission>ManageWeb</pnp:Permission>
                <pnp:Permission>AnonymousSearchAccessWebLists</pnp:Permission>
                <pnp:Permission>UseClientIntegration</pnp:Permission>
                <pnp:Permission>UseRemoteAPIs</pnp:Permission>
                <pnp:Permission>ManageAlerts</pnp:Permission>
                <pnp:Permission>CreateAlerts</pnp:Permission>
                <pnp:Permission>EditMyUserInfo</pnp:Permission>
                <pnp:Permission>EnumeratePermissions</pnp:Permission>
              </pnp:Permissions>
            </pnp:RoleDefinition>
            <pnp:RoleDefinition Name="Project Managers (Microsoft Project Web App)" Description="Users who have published this project or who have Save Project permission in Microsoft Project Web App.">
              <pnp:Permissions>
                <pnp:Permission>EmptyMask</pnp:Permission>
                <pnp:Permission>ViewListItems</pnp:Permission>
                <pnp:Permission>AddListItems</pnp:Permission>
                <pnp:Permission>EditListItems</pnp:Permission>
                <pnp:Permission>DeleteListItems</pnp:Permission>
                <pnp:Permission>ApproveItems</pnp:Permission>
                <pnp:Permission>OpenItems</pnp:Permission>
                <pnp:Permission>ViewVersions</pnp:Permission>
                <pnp:Permission>DeleteVersions</pnp:Permission>
                <pnp:Permission>CancelCheckout</pnp:Permission>
                <pnp:Permission>ManagePersonalViews</pnp:Permission>
                <pnp:Permission>ManageLists</pnp:Permission>
                <pnp:Permission>ViewFormPages</pnp:Permission>
                <pnp:Permission>Open</pnp:Permission>
                <pnp:Permission>ViewPages</pnp:Permission>
                <pnp:Permission>AddAndCustomizePages</pnp:Permission>
                <pnp:Permission>ApplyThemeAndBorder</pnp:Permission>
                <pnp:Permission>ApplyStyleSheets</pnp:Permission>
                <pnp:Permission>CreateSSCSite</pnp:Permission>
                <pnp:Permission>CreateGroups</pnp:Permission>
                <pnp:Permission>ManagePermissions</pnp:Permission>
                <pnp:Permission>BrowseDirectories</pnp:Permission>
                <pnp:Permission>BrowseUserInfo</pnp:Permission>
                <pnp:Permission>AddDelPrivateWebParts</pnp:Permission>
                <pnp:Permission>UpdatePersonalWebParts</pnp:Permission>
                <pnp:Permission>UseClientIntegration</pnp:Permission>
                <pnp:Permission>UseRemoteAPIs</pnp:Permission>
                <pnp:Permission>CreateAlerts</pnp:Permission>
                <pnp:Permission>EditMyUserInfo</pnp:Permission>
              </pnp:Permissions>
            </pnp:RoleDefinition>
            <pnp:RoleDefinition Name="Team members (Microsoft Project Web App)" Description="Users who have assignments in this project in Microsoft Project Web App.">
              <pnp:Permissions>
                <pnp:Permission>EmptyMask</pnp:Permission>
                <pnp:Permission>ViewListItems</pnp:Permission>
                <pnp:Permission>AddListItems</pnp:Permission>
                <pnp:Permission>EditListItems</pnp:Permission>
                <pnp:Permission>DeleteListItems</pnp:Permission>
                <pnp:Permission>ApproveItems</pnp:Permission>
                <pnp:Permission>OpenItems</pnp:Permission>
                <pnp:Permission>ViewVersions</pnp:Permission>
                <pnp:Permission>DeleteVersions</pnp:Permission>
                <pnp:Permission>ManagePersonalViews</pnp:Permission>
                <pnp:Permission>ViewFormPages</pnp:Permission>
                <pnp:Permission>Open</pnp:Permission>
                <pnp:Permission>ViewPages</pnp:Permission>
                <pnp:Permission>BrowseDirectories</pnp:Permission>
                <pnp:Permission>BrowseUserInfo</pnp:Permission>
                <pnp:Permission>AddDelPrivateWebParts</pnp:Permission>
                <pnp:Permission>UpdatePersonalWebParts</pnp:Permission>
                <pnp:Permission>UseClientIntegration</pnp:Permission>
                <pnp:Permission>UseRemoteAPIs</pnp:Permission>
                <pnp:Permission>CreateAlerts</pnp:Permission>
                <pnp:Permission>EditMyUserInfo</pnp:Permission>
              </pnp:Permissions>
            </pnp:RoleDefinition>
            <pnp:RoleDefinition Name="Readers (Microsoft Project Web App)" Description="Users who have been added to this project in Microsoft Project Web App, but not assigned to tasks.">
              <pnp:Permissions>
                <pnp:Permission>EmptyMask</pnp:Permission>
                <pnp:Permission>ViewListItems</pnp:Permission>
                <pnp:Permission>OpenItems</pnp:Permission>
                <pnp:Permission>ViewVersions</pnp:Permission>
                <pnp:Permission>ViewFormPages</pnp:Permission>
                <pnp:Permission>Open</pnp:Permission>
                <pnp:Permission>ViewPages</pnp:Permission>
                <pnp:Permission>BrowseUserInfo</pnp:Permission>
                <pnp:Permission>UseClientIntegration</pnp:Permission>
                <pnp:Permission>UseRemoteAPIs</pnp:Permission>
                <pnp:Permission>CreateAlerts</pnp:Permission>
              </pnp:Permissions>
            </pnp:RoleDefinition>
            <pnp:RoleDefinition Name="PS Project Manger" Description="Permission level for the project manager group on the project site">
              <pnp:Permissions>
                <pnp:Permission>EmptyMask</pnp:Permission>
                <pnp:Permission>ViewListItems</pnp:Permission>
                <pnp:Permission>AddListItems</pnp:Permission>
                <pnp:Permission>EditListItems</pnp:Permission>
                <pnp:Permission>DeleteListItems</pnp:Permission>
                <pnp:Permission>ApproveItems</pnp:Permission>
                <pnp:Permission>OpenItems</pnp:Permission>
                <pnp:Permission>ViewVersions</pnp:Permission>
                <pnp:Permission>DeleteVersions</pnp:Permission>
                <pnp:Permission>ViewFormPages</pnp:Permission>
                <pnp:Permission>Open</pnp:Permission>
                <pnp:Permission>ViewPages</pnp:Permission>
                <pnp:Permission>BrowseDirectories</pnp:Permission>
                <pnp:Permission>BrowseUserInfo</pnp:Permission>
                <pnp:Permission>UseClientIntegration</pnp:Permission>
                <pnp:Permission>UseRemoteAPIs</pnp:Permission>
                <pnp:Permission>CreateAlerts</pnp:Permission>
              </pnp:Permissions>
            </pnp:RoleDefinition>
            <pnp:RoleDefinition Name="PS Core Team" Description="Permission level for Core team members in the project site.">
              <pnp:Permissions>
                <pnp:Permission>EmptyMask</pnp:Permission>
                <pnp:Permission>ViewListItems</pnp:Permission>
                <pnp:Permission>AddListItems</pnp:Permission>
                <pnp:Permission>EditListItems</pnp:Permission>
                <pnp:Permission>OpenItems</pnp:Permission>
                <pnp:Permission>ViewFormPages</pnp:Permission>
                <pnp:Permission>Open</pnp:Permission>
                <pnp:Permission>ViewPages</pnp:Permission>
                <pnp:Permission>BrowseDirectories</pnp:Permission>
                <pnp:Permission>BrowseUserInfo</pnp:Permission>
                <pnp:Permission>UseClientIntegration</pnp:Permission>
                <pnp:Permission>UseRemoteAPIs</pnp:Permission>
                <pnp:Permission>CreateAlerts</pnp:Permission>
              </pnp:Permissions>
            </pnp:RoleDefinition>
            <pnp:RoleDefinition Name="PS Finance" Description="The permission level for finance group users">
              <pnp:Permissions>
                <pnp:Permission>EmptyMask</pnp:Permission>
                <pnp:Permission>ViewListItems</pnp:Permission>
                <pnp:Permission>AddListItems</pnp:Permission>
                <pnp:Permission>EditListItems</pnp:Permission>
                <pnp:Permission>DeleteListItems</pnp:Permission>
                <pnp:Permission>OpenItems</pnp:Permission>
                <pnp:Permission>ViewVersions</pnp:Permission>
                <pnp:Permission>ViewFormPages</pnp:Permission>
                <pnp:Permission>Open</pnp:Permission>
                <pnp:Permission>ViewPages</pnp:Permission>
                <pnp:Permission>BrowseDirectories</pnp:Permission>
                <pnp:Permission>BrowseUserInfo</pnp:Permission>
                <pnp:Permission>UseClientIntegration</pnp:Permission>
                <pnp:Permission>UseRemoteAPIs</pnp:Permission>
                <pnp:Permission>CreateAlerts</pnp:Permission>
              </pnp:Permissions>
            </pnp:RoleDefinition>
          </pnp:RoleDefinitions>
        </pnp:Permissions>
      </pnp:Security>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>
```

Once the levels are created, create a project and its OOTB project site.  Then run the following template which is where we are finding the performance issue against the site:
```
<?xml version="1.0"?>
<pnp:Provisioning 
  xmlns:pnp="http://schemas.dev.office.com/PnP/2017/05/ProvisioningSchema">
	<pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.7.1609.3, Culture=neutral, PublicKeyToken=3751622786b357c2">
		<pnp:Parameters>
			<pnp:Parameter Key="TemplateName">Client Project</pnp:Parameter>
			<pnp:Parameter Key="ProjectSiteCollection">/sites/PWA-CH_Dev-Fusion</pnp:Parameter>
			 <pnp:Parameter Key="TemplateAppliedDate"> {datenow} </pnp:Parameter> 
		</pnp:Parameters>
	</pnp:Preferences>
	<pnp:Templates ID="CONTAINER-TEMPLATE-8830EE90272C4742AE1C0C3C8C95E2A0">
		<pnp:ProvisioningTemplate ID="Client-Project-Provisioning" Version="1" BaseSiteTemplate="PROJECTSITE#0">
			<pnp:Security BreakRoleInheritance="true" CopyRoleAssignments="false" ClearSubscopes="true">
				<pnp:SiteGroups>
					<pnp:SiteGroup Title="{siteid} - CH Project Managers" Description="" Owner="{associatedownergroup}" AllowMembersEditMembership="false" AllowRequestToJoinLeave="false" AutoAcceptRequestToJoinLeave="false" OnlyAllowMembersViewMembership="false"/>
					<pnp:SiteGroup Title="{siteid} - CH Finance Users" Description="" Owner="{associatedownergroup}" AllowMembersEditMembership="true" AllowRequestToJoinLeave="false" AutoAcceptRequestToJoinLeave="false" OnlyAllowMembersViewMembership="true"/>
					<pnp:SiteGroup Title="{siteid} - CH-Core Team" Description="" Owner="{associatedownergroup}" AllowMembersEditMembership="false" AllowRequestToJoinLeave="false" AutoAcceptRequestToJoinLeave="false" OnlyAllowMembersViewMembership="true"/>
				</pnp:SiteGroups>
				<pnp:Permissions>
					<pnp:RoleAssignments>
						<pnp:RoleAssignment Principal="{siteid} - CH Finance Users" RoleDefinition="PS Finance" />
						<pnp:RoleAssignment Principal="{siteid} - CH Project Managers" RoleDefinition="PS Project Manger" />
						<pnp:RoleAssignment Principal="{siteid} - CH-Core Team" RoleDefinition="PS Core Team" />
					</pnp:RoleAssignments>
				</pnp:Permissions>
			</pnp:Security>
			<pnp:Lists>
			<pnp:ListInstance Title="Forecast Region Sales" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/ForecastRegionSales" EnableVersioning="true" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-de22-43b2-a848-c05709900100" ContentTypesEnabled="true" EnableFolderCreation="false">
				<pnp:Security>
						<pnp:BreakRoleInheritance CopyRoleAssignments="false" ClearSubscopes="false">
							<pnp:RoleAssignment Principal="Administrators for Project Web App" RoleDefinition="Full Control" />
							<pnp:RoleAssignment Principal="{associatedownergroup}" RoleDefinition="Full Control" />
							<pnp:RoleAssignment Principal="{associatedownergroup}" RoleDefinition="Web Administrators (Microsoft Project Web App)" />
							<pnp:RoleAssignment Principal="{siteid} - CH Finance Users" RoleDefinition="PS Finance" />
							<pnp:RoleAssignment Principal="{siteid} - CH Project Managers" RoleDefinition="PS Project Manger" />
						</pnp:BreakRoleInheritance>
					</pnp:Security>
				</pnp:ListInstance>
				<pnp:ListInstance Title="Market Sales" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/Market Sales" EnableVersioning="true" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-de22-43b2-a848-c05709900100" ContentTypesEnabled="true" EnableFolderCreation="false">
					<pnp:Security>
						<pnp:BreakRoleInheritance CopyRoleAssignments="false" ClearSubscopes="false">
							<pnp:RoleAssignment Principal="Administrators for Project Web App" RoleDefinition="Full Control" />
							<pnp:RoleAssignment Principal="{associatedownergroup}" RoleDefinition="Full Control" />
							<pnp:RoleAssignment Principal="{associatedownergroup}" RoleDefinition="Web Administrators (Microsoft Project Web App)" />
							<pnp:RoleAssignment Principal="{siteid} - CH Finance Users" RoleDefinition="PS Finance" />
							<pnp:RoleAssignment Principal="{siteid} - CH Project Managers" RoleDefinition="PS Project Manger" />
						</pnp:BreakRoleInheritance>
					</pnp:Security>
				</pnp:ListInstance>
				<pnp:ListInstance Title="In Scope Finance Markets" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/In Scope Finance Markets" EnableVersioning="true" MinorVersionLimit="0" MaxVersionLimit="20" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-de22-43b2-a848-c05709900100" ContentTypesEnabled="true" EnableFolderCreation="false">
					<pnp:Security>
						<pnp:BreakRoleInheritance CopyRoleAssignments="false" ClearSubscopes="false">
							<pnp:RoleAssignment Principal="Administrators for Project Web App" RoleDefinition="Full Control" />
							<pnp:RoleAssignment Principal="{associatedownergroup}" RoleDefinition="Full Control" />
							<pnp:RoleAssignment Principal="{associatedownergroup}" RoleDefinition="Web Administrators (Microsoft Project Web App)" />
							<pnp:RoleAssignment Principal="{siteid} - CH Finance Users" RoleDefinition="PS Finance" />
							<pnp:RoleAssignment Principal="{siteid} - CH Project Managers" RoleDefinition="PS Project Manger" />
						</pnp:BreakRoleInheritance>
					</pnp:Security>
				</pnp:ListInstance>
				</pnp:Lists>
		</pnp:ProvisioningTemplate>
	</pnp:Templates>
</pnp:Provisioning>
```

**Comment by MattPPMConsultant** [comment]
I have captured the Error returned via the provisioning engine.  There is a 401 error when trying to apply the role assignment to multiple sites concurrently.

```
The remote server returned an error: (401) Unauthorized.
at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.Execute()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at Microsoft.SharePoint.Client.ClientObjectExtensions.EnsureProperty[T,TResult](T clientObject, Expression`1 propertySelector)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectSiteSecurity.GetPrincipal(Web web, TokenParser parser, PnPMonitoredScope scope, IEnumerable`1 groups, RoleAssignment roleAssignment)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectSiteSecurity.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo)
   at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)
   at Supplier.SharePointOnline.RemoteProvisioning.ApplyJob.Functions.ProcessQueueMessageInner(TemplateRequest templateRequest, TextWriter log) in C:\src\Supplier.Client.RemoteProvisioning\Supplier.SharePointOnline.RemoteProvisioning.ApplyJob\Functions.cs:line 105
   at Supplier.SharePointOnline.RemoteProvisioning.ApplyJob.Functions.ProcessQueueMessage(AzureQueueMessage message, TextWriter log) in C:\src\Supplier.Client.RemoteProvisioning\Supplier.SharePointOnline.RemoteProvisioning.ApplyJob\Functions.cs:line 133
```

**Comment by MattPPMConsultant** [comment]
Been testing the Security application and it looks like @HLethaus has aced this fix. thanks
