### ISSUE TITLE
XMLFileSystemTemplateProvider.saveAs method throws a Reflection error

### ISSUE THREAD

**Issue by ravenboilinux** [SharePoint/PnP-Sites-Core#1526]
#### Category
[ X] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ X] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
March 2017 CU
#### Expected or Desired Behavior
The ability to save ProvisioningTemplate template to xml file

#### Observed Behavior
using the XMLFileSystemTemplateProvider.saveAs method produces this error message:
System.Reflection.ReflectionTypeLoadException: 'Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.'
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XmlPnPSchemaBaseSerializer`1.SerializeTemplate(ProvisioningTemplate template, Object persistenceTemplate)
   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLPnPSchemaV201705Serializer.SerializeTemplate(ProvisioningTemplate template, Object persistenceTemplate)
   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XmlPnPSchemaBaseSerializer`1.ToFormattedTemplate(ProvisioningTemplate template)
   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLPnPSchemaFormatter.ToFormattedTemplate(ProvisioningTemplate template)
   at OfficeDevPnP.Core.Framework.Provisioning.Providers.TemplateProviderBase.SaveToConnector(ProvisioningTemplate template, String uri, ITemplateFormatter formatter, ITemplateProviderExtension[] extensions)
   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLTemplateProvider.SaveAs(ProvisioningTemplate template, String uri, ITemplateFormatter formatter, ITemplateProviderExtension[] extensions)
   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLTemplateProvider.SaveAs(ProvisioningTemplate template, String uri, ITemplateProviderExtension[] extensions)
   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLTemplateProvider.SaveAs(ProvisioningTemplate template, String uri)
   at ConsoleApp10.Program.GetProvisioningTemplate(ConsoleColor defaultForeground, String webUrl)
   at ConsoleApp10.Program.Main(String[] args)

#### Steps to Reproduce
where template is a ProvisioningTemplate 
                XMLFileSystemTemplateProvider provider = new XMLFileSystemTemplateProvider(@"c:\temp\pnpprovisioningdemo", "");
                string templateName = "template.xml";
                provider.SaveAs(template, templateName);

**Comment by ravenboilinux** [comment]
digging a bit deeper i was able to find this error in the LoaderExceptions 

Could not load file or assembly 'SharePointPnP.IdentityModel.Extensions, Version=1.2.3.0, Culture=neutral, PublicKeyToken=5e633289e95c321a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by ravenboilinux** [comment]
The version that nuget install was the 1.2.2.0 version not the 1.2.3.0 version

**Comment by jansenbe** [comment]
I've unlisted all versions except 1.2.3 and in my testing this version is retrieved. There's no functional difference between 1.2.2. and 1.2.3, it's only a change in strongname and authenticode signing. Can you confirm this fixes your problem

**Comment by ravenboilinux** [comment]
Yes this does fix my issue. Thank you.
