### ISSUE TITLE
Provisioning Modern Site / Page with custom web part is not working

### ISSUE THREAD

**Issue by gboraiah** [SharePoint/PnP-Sites-Core#1578]
Am using PnP core framework to dynamically provision modern site along with the custom web parts developed using SPFx. 
The following code fails with an error as mentioned below;
 // Associate file connector for assets
                        FileSystemConnector connector = new FileSystemConnector(@"c:\tmp\myprovisioning", "Gavi");
                        baseTemplate.Connector = connector;
                        web.ApplyProvisioningTemplate(baseTemplate, ptaInfo);

ERROR 
February 06, 2018 18:48:19, 018 [1] INFO SiteProvisioningUtility.Program - 1|9-Regional Settings
February 06, 2018 18:48:19, 353 [1] INFO SiteProvisioningUtility.Program - 2|9-Site Security
February 06, 2018 18:48:21, 557 [1] INFO SiteProvisioningUtility.Program - 3|9-Features
February 06, 2018 18:48:26, 842 [1] INFO SiteProvisioningUtility.Program - 4|9-List instances
February 06, 2018 18:54:45, 278 [1] INFO SiteProvisioningUtility.Program - 5|9-Tenant Settings
February 06, 2018 18:54:45, 294 [1] INFO SiteProvisioningUtility.Program - 6|9-Application Lifecycle Management
February 06, 2018 18:54:56, 309 [1] INFO SiteProvisioningUtility.Program - 7|9-ClientSidePages
February 06, 2018 18:55:01, 356 [1] ERROR SiteProvisioningUtility.Program - Error occurred while applying the template :System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectClientSidePages.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo)
   at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)
   at SiteProvisioningUtility.Program.ApplyWebTemplate() in D:\Source Code\Gavi\\SiteProvisioningUtility\SiteProvisioningUtility\Program.cs:line 179

**Comment by jansenbe** [comment]
can you share the template that fails?

**Comment by gboraiah** [comment]
Hi Bert Jansen,

Please find the attached template for your reference.

Thank You,
Gaviyaiah Boraiah

**Comment by gboraiah** [comment]
Hi,

Any clue of what am I missing in this provisioning template?

Thank You,
Gaviyaiah Boraiah

From: Gaviyaiah Boraiah
Sent: 13 February 2018 02:04 PM
To: 'SharePoint/PnP-Sites-Core' <reply@reply.github.com>; SharePoint/PnP-Sites-Core <PnP-Sites-Core@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [SharePoint/PnP-Sites-Core] Provisioning Modern Site / Page with custom web part is not working (#1578)

Hi Bert Jansen,

Please find the attached template for your reference.

Thank You,
Gaviyaiah Boraiah

**Comment by jansenbe** [comment]
Sorry, but I don't see an attached file? Otherwise paste in the relevant clientsidepages section

**Comment by gboraiah** [comment]
Bert,

Please find the attached file as well as the clientsidepages section of the template here for your reference.
Thank you very much for your help;

<pnp:ClientSidePages>
        <pnp:ClientSidePage PageName="Home.aspx" PromoteAsNewsArticle="false" Overwrite="true" Layout="Home" EnableComments="false">
          <pnp:Sections>
            <pnp:Section Order="1" Type="OneColumnFullWidth">
              <pnp:Controls>
                <pnp:CanvasControl WebPartType="Hero" JsonControlData="{ &quot;serverProcessedContent&quot;: {&quot;htmlStrings&quot;:{},&quot;searchablePlainTexts&quot;:{&quot;content[0].title&quot;:&quot;Welcome! Click Edit at the top right of the page to start customizing&quot;,&quot;content[1].title&quot;:&quot;Learn more about your Communication site&quot;,&quot;content[2].title&quot;:&quot;Customize this tile with your own title, image and link&quot;,&quot;content[3].title&quot;:&quot;Customize this tile with your own title, image and link&quot;,&quot;content[4].title&quot;:&quot;Customize this tile with your own title, image and link&quot;,&quot;content[0].alternateText&quot;:&quot;People in a casual meeting&quot;,&quot;content[1].alternateText&quot;:&quot;&quot;,&quot;content[2].alternateText&quot;:&quot;Two people talking in a stairway&quot;,&quot;content[3].alternateText&quot;:&quot;Office building architecture&quot;,&quot;content[4].alternateText&quot;:&quot;Office lobby with couches&quot;,&quot;content[0].callToActionText&quot;:&quot;LEARN MORE&quot;},&quot;imageSources&quot;:{&quot;content[0].image.url&quot;:&quot;/_LAYOUTS/IMAGES/REPORTSITEDEFAULTIMAGE1.PNG&quot;,&quot;content[1].image.url&quot;:&quot;/_LAYOUTS/IMAGES/REPORTSITEDEFAULTIMAGE2.PNG&quot;,&quot;content[2].image.url&quot;:&quot;/_LAYOUTS/IMAGES/REPORTSITEDEFAULTIMAGE3.PNG&quot;,&quot;content[3].image.url&quot;:&quot;/_LAYOUTS/IMAGES/REPORTSITEDEFAULTIMAGE4.PNG&quot;,&quot;content[4].image.url&quot;:&quot;/_LAYOUTS/IMAGES/REPORTSITEDEFAULTIMAGE5.PNG&quot;,&quot;content[0].previewImage.url&quot;:&quot;https://go.microsoft.com/fwlink/?linkid=841917&quot;,&quot;content[1].previewImage.url&quot;:&quot;https://go.microsoft.com/fwlink/?linkid=841918&quot;,&quot;content[2].previewImage.url&quot;:&quot;https://go.microsoft.com/fwlink/?linkid=841918&quot;,&quot;content[3].previewImage.url&quot;:&quot;https://go.microsoft.com/fwlink/?linkid=841918&quot;,&quot;content[4].previewImage.url&quot;:&quot;https://go.microsoft.com/fwlink/?linkid=841918&quot;},&quot;links&quot;:{&quot;content[0].link&quot;:&quot;https://go.microsoft.com/fwlink/?linkid=841917&quot;,&quot;content[1].link&quot;:&quot;https://go.microsoft.com/fwlink/?linkid=841918&quot;,&quot;content[2].link&quot;:&quot;https://go.microsoft.com/fwlink/?linkid=841918&quot;,&quot;content[3].link&quot;:&quot;https://go.microsoft.com/fwlink/?linkid=841918&quot;,&quot;content[4].link&quot;:&quot;https://go.microsoft.com/fwlink/?linkid=841918&quot;,&quot;content[0].callToActionLink&quot;:&quot;https://go.microsoft.com/fwlink/?linkid=841917&quot;}}, &quot;properties&quot;: {&quot;layoutCategory&quot;:1,&quot;layout&quot;:5,&quot;content&quot;:[{&quot;id&quot;:&quot;e38b7aa6-a9cd-47eb-9ef2-efb5f7084bcf&quot;,&quot;type&quot;:&quot;UrlLink&quot;,&quot;color&quot;:4,&quot;image&quot;:{&quot;siteId&quot;:&quot;e4901b7f-35d5-444f-a697-453091a4ae3b&quot;,&quot;webId&quot;:&quot;2d4695fc-97f1-4c8a-affc-1eb117ef047d&quot;,&quot;id&quot;:&quot;e6f07493-0021-4cd6-be6f-ad0049c950a3&quot;},&quot;description&quot;:&quot;&quot;,&quot;showDescription&quot;:false,&quot;showTitle&quot;:true,&quot;imageDisplayOption&quot;:3,&quot;isDefaultImage&quot;:true,&quot;showCallToAction&quot;:true,&quot;isDefaultImageLoaded&quot;:false,&quot;isCustomImageLoaded&quot;:true,&quot;previewImage&quot;:{}},{&quot;id&quot;:&quot;8adee762-0dc5-48fd-94ef-eb391e8ec58f&quot;,&quot;type&quot;:&quot;UrlLink&quot;,&quot;color&quot;:5,&quot;image&quot;:{&quot;siteId&quot;:&quot;e4901b7f-35d5-444f-a697-453091a4ae3b&quot;,&quot;webId&quot;:&quot;2d4695fc-97f1-4c8a-affc-1eb117ef047d&quot;,&quot;id&quot;:&quot;8bae98ae-9fcd-4d9b-a8c1-2b9f879d01db&quot;},&quot;description&quot;:&quot;&quot;,&quot;showDescription&quot;:false,&quot;showTitle&quot;:true,&quot;imageDisplayOption&quot;:2,&quot;isDefaultImage&quot;:true,&quot;showCallToAction&quot;:false,&quot;isDefaultImageLoaded&quot;:false,&quot;isCustomImageLoaded&quot;:true,&quot;previewImage&quot;:{}},{&quot;id&quot;:&quot;cc618d86-dc33-4742-9df0-e2f714df1f78&quot;,&quot;type&quot;:&quot;UrlLink&quot;,&quot;color&quot;:4,&quot;image&quot;:{&quot;siteId&quot;:&quot;e4901b7f-35d5-444f-a697-453091a4ae3b&quot;,&quot;webId&quot;:&quot;2d4695fc-97f1-4c8a-affc-1eb117ef047d&quot;,&quot;id&quot;:&quot;96a4cbdb-43e3-4458-855e-37464b9dddc1&quot;},&quot;description&quot;:&quot;&quot;,&quot;showDescription&quot;:false,&quot;showTitle&quot;:true,&quot;imageDisplayOption&quot;:3,&quot;isDefaultImage&quot;:true,&quot;showCallToAction&quot;:false,&quot;isDefaultImageLoaded&quot;:false,&quot;isCustomImageLoaded&quot;:true,&quot;previewImage&quot;:{}},{&quot;id&quot;:&quot;a1098565-46ce-45a3-ad6f-e2c350cd2ddc&quot;,&quot;type&quot;:&quot;UrlLink&quot;,&quot;color&quot;:4,&quot;image&quot;:{&quot;siteId&quot;:&quot;e4901b7f-35d5-444f-a697-453091a4ae3b&quot;,&quot;webId&quot;:&quot;2d4695fc-97f1-4c8a-affc-1eb117ef047d&quot;,&quot;id&quot;:&quot;a46624cb-32f9-4e8e-a632-8e0620c07bcb&quot;},&quot;description&quot;:&quot;&quot;,&quot;showDescription&quot;:false,&quot;showTitle&quot;:true,&quot;imageDisplayOption&quot;:3,&quot;isDefaultImage&quot;:true,&quot;showCallToAction&quot;:false,&quot;isDefaultImageLoaded&quot;:false,&quot;isCustomImageLoaded&quot;:true,&quot;previewImage&quot;:{}},{&quot;id&quot;:&quot;9d2f7147-4b93-478a-8e2a-c1d7d20356b2&quot;,&quot;type&quot;:&quot;UrlLink&quot;,&quot;color&quot;:4,&quot;image&quot;:{&quot;siteId&quot;:&quot;e4901b7f-35d5-444f-a697-453091a4ae3b&quot;,&quot;webId&quot;:&quot;2d4695fc-97f1-4c8a-affc-1eb117ef047d&quot;,&quot;id&quot;:&quot;016d7643-a082-4e6e-8612-943307efa6e2&quot;},&quot;description&quot;:&quot;&quot;,&quot;showDescription&quot;:false,&quot;showTitle&quot;:true,&quot;imageDisplayOption&quot;:3,&quot;isDefaultImage&quot;:true,&quot;showCallToAction&quot;:false,&quot;isDefaultImageLoaded&quot;:false,&quot;isCustomImageLoaded&quot;:true,&quot;previewImage&quot;:{}}],&quot;isFullWidth&quot;:true}}" ControlId="c4bd7b2f-7b6e-4599-8485-16504575f590" Order="1" Column="1" />
              </pnp:Controls>
            </pnp:Section>
            <pnp:Section Order="2" Type="ThreeColumn">
              <pnp:Controls>
                <pnp:CanvasControl WebPartType="Custom" JsonControlData="{ &quot;serverProcessedContent&quot;: {&quot;htmlStrings&quot;:{},&quot;searchablePlainTexts&quot;:{},&quot;imageSources&quot;:{},&quot;links&quot;:{}}, &quot;properties&quot;: {&quot;description&quot;:&quot;UpcomingEvents&quot;,&quot;wpHeading&quot;:&quot;Upcoming Events&quot;,&quot;daysToDisplay&quot;:&quot;120&quot;,&quot;itemsToDisplay&quot;:&quot;5&quot;,&quot;CalendarList&quot;:&quot;{listid:Events}||Events&quot;}}" ControlId="141d1dc5-2ff3-46e1-b02e-b7a1c4e45cfd" Order="1" Column="1" />
                <pnp:CanvasControl WebPartType="Custom" JsonControlData="{ &quot;serverProcessedContent&quot;: {&quot;htmlStrings&quot;:{},&quot;searchablePlainTexts&quot;:{},&quot;imageSources&quot;:{},&quot;links&quot;:{}}, &quot;properties&quot;: {&quot;description&quot;:&quot;QuickPoll&quot;,&quot;wpHeading&quot;:&quot;Quick Poll&quot;,&quot;surveyListName&quot;:&quot;{listid:Quick Poll Questions}||Quick Poll Questions&quot;,&quot;answersList&quot;:&quot;{listid:Quick Poll Answers}||Quick Poll Answers&quot;}}" ControlId="65d66cb6-c0ef-4229-8125-869164ee7e55" Order="1" Column="2" />
                <pnp:CanvasControl WebPartType="Custom" JsonControlData="{ &quot;serverProcessedContent&quot;: {&quot;htmlStrings&quot;:{},&quot;searchablePlainTexts&quot;:{},&quot;imageSources&quot;:{},&quot;links&quot;:{}}, &quot;properties&quot;: {&quot;description&quot;:&quot;ErgSpotlight&quot;,&quot;wpHeading&quot;:&quot;ERG Spotlight&quot;,&quot;listName&quot;:&quot;{listid:Spotlight}||Spotlight&quot;}}" ControlId="46fd7c5e-3306-499c-ac84-f5fc865040da" Order="1" Column="3" />
              </pnp:Controls>
            </pnp:Section>
          </pnp:Sections>
        </pnp:ClientSidePage>
      </pnp:ClientSidePages>

Thank You,
Gaviyaiah Boraiah

**Comment by gboraiah** [comment]
Thank you Jansen!!!

Really appreciate the help.

Thank You,
Gaviyaiah Boraiah
