### ISSUE TITLE
Simple template fails - Invalid Template

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/PnP-Sites-Core#1615]
#### Which PnP repository should you use to report the issue? 
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*
- PnP Samples - https://github.com/OfficeDev/PnP
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP JS Core - https://github.com/OfficeDev/PnP-JS-Core
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[ X] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Simple Template should work :- 

<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2018/01/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.23.1802.0, Culture=neutral, PublicKeyToken=5e633289e95c321a" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-F8BEC8CB1F544566AD5CF8EC5BF9BEF3">
    <pnp:ProvisioningTemplate ID="TEMPLATE-F8BEC8CB1F544566AD5CF8EC5BF9BEF3" Version="1" BaseSiteTemplate="STS#0" Scope="RootSite">
		<pnp:ListInstance Title="Cheque" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/Cheque" >
        </pnp:ListInstance>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>

#### Observed Behavior

PS C:\\documents\PowerShell Scripts\SharePointOnline\Tenant Migration> Apply-pnpprovisioningtemplate
 -Path "C:\\Documents\PowerShell Scripts\SharePointOnline\Tenant Migration\Templates\ChequesList.xml
"
powershell.exe Information: 0 : 2018-02-25 11:08:24.1281        [OfficeDevPnP.Core]     [0]     [Information]   File ChequesList.xml retrieved from folder      0ms
powershell.exe Information: 0 : 2018-02-25 11:08:24.1281        [OfficeDevPnP.Core]     [0]     [Information]   File ChequesList.xml retrieved from folder      0ms
Apply-pnpprovisioningtemplate : The provided template is not valid!
At line:1 char:1
+ Apply-pnpprovisioningtemplate -Path "C:\Users\price\OneDrive\Document ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ApplicationException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

PS C:\documents\PowerShell Scripts\SharePointOnline\Tenant Migration> $error[0].Exception.ToString(
)
System.ApplicationException: The provided template is not valid!
   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XmlPnPSchemaBaseSerializer`1.ProcessInputStream(Stream template, String identifier, ProvisioningTemplate result)
   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XmlPnPSchemaBaseSerializer`1.ToProvisioningTemplate(Stream template, String identifier)
   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLPnPSchemaFormatter.ToProvisioningTemplate(Stream template, String identifier)
   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLTemplateProvider.GetTemplate(String uri, String identifier, ITemplateFormatter formatter, ITemplateProviderExtension[] extensions)
   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLTemplateProvider.GetTemplate(String uri, ITemplateProviderExtension[] extensions)
   at SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate.ExecuteCmdlet()
   at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()
PS C:\documents\PowerShell Scripts\SharePointOnline\Tenant Migration> $error[0].Exception.InnerExce
ption.ToString()
You cannot call a method on a null-valued expression.
At line:1 char:1
+ $error[0].Exception.InnerException.ToString()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

#### Steps to Reproduce
Run Apply-PnPProvisioningTemplate against the above template

 Sharing is caring.

**Comment by rgylesbedford** [comment]
pnp:ListInstance needs to be inside a [pnp:Lists](https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2018-01.md#lists) element in order to be a valid template
