### ISSUE TITLE
Setting All Day Event to True Casues Invalid Date/Time Value when inputting data into the OOTB Events List

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/PnP-Sites-Core#1629]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Which PnP repository should you use to report the issue? 
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*
- PnP Samples - https://github.com/OfficeDev/PnP
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP JS Core - https://github.com/OfficeDev/PnP-JS-Core
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
setting fAllDayEvent Boolean field to true should not cause any issues,

#### Observed Behavior
Setting fAllDayEvent to true causes an error  -

powershell.exe Error: 0 : 2018-02-28 13:11:46.4833      [List instances Data Rows]      [9]     [Error] Creating listite
m failed: Invalid date/time value.

```
A date/time field contains invalid data. Please check the value and try again. :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstanceDataRows.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)      4233ms  503c5f18-f58f-41a7-8c64-887d7fa5e956
powershell.exe Information: 0 : 2018-02-28 13:11:46.5253        [List instances Data Rows]      [9]     [Debug] Code execution scope ended      4275ms  503c5f18-f58f-41a7-8c64-887d7fa5e956

```

#### Steps to Reproduce
use this provisioningTemplate -

```
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2018/01/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.23.1802.0, Culture=neutral, PublicKeyToken=5e633289e95c321a" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-F8BEC8CB1F544566AD5CF8EC5BF9BEF3">
    <pnp:ProvisioningTemplate ID="TEMPLATE-F8BEC8CB1F544566AD5CF8EC5BF9BEF3" Version="1" BaseSiteTemplate="STS#0" Scope="RootSite">
      <pnp:WebSettings RequestAccessEmail="someone@example.com" NoCrawl="false" WelcomePage="SitePages/Home.aspx" SiteLogo="{site}/SiteAssets/cards tile.jpg" AlternateCSS="" MasterPageUrl="{masterpagecatalog}/seattle.master" CustomMasterPageUrl="{masterpagecatalog}/seattle.master" />
      <pnp:RegionalSettings AdjustHijriDays="0" AlternateCalendarType="None" CalendarType="Gregorian" Collation="25" FirstDayOfWeek="Monday" FirstWeekOfYear="2" LocaleId="2057" ShowWeeks="false" Time24="true" TimeZone="2" WorkDayEndHour="5:00PM" WorkDays="62" WorkDayStartHour="8:00AM" />
      <pnp:Lists>
        <pnp:ListInstance Title="Events" Description="" DocumentTemplate="" TemplateType="106" Url="Events" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-ec85-4903-972d-ebe475780106" ContentTypesEnabled="true" EnableFolderCreation="false" DefaultDisplayFormUrl="{site}/Events/DispForm.aspx" DefaultEditFormUrl="{site}/Events/EditForm.aspx" DefaultNewFormUrl="{site}/Events/NewForm.aspx" ImageUrl="/_layouts/15/images/itevent.png?rev=44" IsApplicationList="false" ValidationFormula="" ValidationMessage="">
          <pnp:DataRows xmlns:pnp="http://schemas.dev.office.com/PnP/2018/01/ProvisioningSchema">
            <pnp:DataRow>
              <pnp:DataValue FieldName="Title">Staff conference</pnp:DataValue>
              <pnp:DataValue FieldName="Location">AJ Bell Stadium, Salford, United Kingdom</pnp:DataValue>
              <pnp:DataValue FieldName="EventDate">31/01/2018 00:00:00</pnp:DataValue>
               <pnp:DataValue FieldName="Description">&lt;p&gt;THis is very important too&lt;/p&gt;</pnp:DataValue>
              <pnp:DataValue FieldName="fAllDayEvent">True</pnp:DataValue>
              <pnp:DataValue FieldName="fRecurrence">False</pnp:DataValue>
              <pnp:DataValue FieldName="EventType">0</pnp:DataValue>
              <pnp:DataValue FieldName="Duration">86340</pnp:DataValue>
<!--              <pnp:DataValue FieldName="ParticipantsPicker" />  -->
              <pnp:DataValue FieldName="Category">Business</pnp:DataValue>
<!--              <pnp:DataValue FieldName="Participants" />  -->
              <pnp:DataValue FieldName="BannerUrl">https://stylesandwood.sharepoint.com/sites/jigsaw/SiteAssets/SitePages/qs40qgrf/71825-H-M.jpg?X=50.44195639363582&amp;Y=32.7428572518485&amp;Id={71DEC1D9-EED2-43EE-9442-5F3C91C8575B}&amp;listId=6944f412-2a1f-468f-bffe-5f9496291786</pnp:DataValue>
            </pnp:DataRow>
           </pnp:DataRows>
        </pnp:ListInstance>
      </pnp:Lists>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>

```

Sharing is caring.

**Comment by erwinvanhunen** [comment]
Hi! We identified a rather obscure use case with the engine which is effectively related to the fAllDayEvent field. We are working on a fix as we speak (which will also fix some other related issues).

**Comment by erwinvanhunen** [comment]
We updated the engine to handle this case. The March release of PnP PowerShell and PnP Sites Core will contain this fix.
