### ISSUE TITLE
Can't apply a template with schema version 2017/05 including <ClientSidePages />

### ISSUE THREAD

**Issue by olemp** [SharePoint/PnP-Sites-Core#1652]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Should be apply to apply a template with schema version 2017/05 including <ClientSidePages />.

#### Observed Behavior
Get the error `Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.`.

Using an Azure Function project with
* SharePointPnP.IdentityModel.Extensions@1.2.3
* Microsoft.IdentityModel.Clients.ActiveDirectory@3.19.0
* Microsoft.NET.Sdk.Functions@1.0.7
* SharePointPnPCoreOnline@2.22.18.01
* Microsoft.Azure.Services.AppAuthentication@1.1.0-preview

```
Error: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XmlPnPSchemaBaseSerializer`1.DeserializeTemplate(Object persistenceTemplate, ProvisioningTemplate template)
   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLPnPSchemaV201705Serializer.DeserializeTemplate(Object persistenceTemplate, ProvisioningTemplate template)
   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XmlPnPSchemaBaseSerializer`1.ToProvisioningTemplate(Stream template, String identifier)
   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLPnPSchemaFormatter.ToProvisioningTemplate(Stream template, String identifier)
   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLTemplateProvider.GetTemplate(String uri, String identifier, ITemplateFormatter formatter, ITemplateProviderExtension[] extensions)
   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLTemplateProvider.GetTemplate(String uri, ITemplateProviderExtension[] extensions)
   at FFOffice365FunctionsApp.SharePoint.ApplyTemplate.ApplyTemplateToWeb(ClientContext clientContext, String templateUrl, String templateFileName, TraceWriter log)
   at FFOffice365FunctionsApp.SharePoint.ApplyTemplate.<Run>d__1.MoveNext()
```

**Comment by olemp** [comment]
LoadExceptions details:

```
Error: Could not load file or assembly 'Microsoft.Graph.Core, Version=1.2.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

Error: Could not load file or assembly 'Microsoft.Graph, Version=1.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
```

**Comment by jansenbe** [comment]
Since we depend on reflection to load types *all* depending assemblies must be available. We did add extra nuget references in latest versions to ensure all dependencies are available...can you cross check with March version?

**Comment by olemp** [comment]
@jansenbe Thanks for a quick reply. Let me check ;)

**Comment by olemp** [comment]
Looks like this combination of packages solve the issue. I had 1.7.0 of Microsoft Graph.

![image](https://user-images.githubusercontent.com/7606007/37093101-6beb3414-220e-11e8-8b34-852a65db20bd.png)

This issue only occured when including ClientSidePages. I guess there's some graph calls to add clientsidepages?

**Comment by ArunRajiv** [comment]
i too facing same issue with SharepointPNPCoreOnline 3.1.1809. But it works fine with powershell commandlets **Apply-PnPProvisioningTemplate** -Path 'E:\WebPartPage.xml' -Connection $Connection. 
Any fix can be provided?
