### ISSUE TITLE
tenant.CreateSiteCollection SiteOwnerLogin Problem

### ISSUE THREAD

**Issue by MrTantum** [SharePoint/PnP-Sites-Core#1674]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Creating a site collection using the pnp function [tenant.CreateSiteCollection](https://msdn.microsoft.com/en-us/pnp_sites_core/microsoft.sharepoint.client.tenantextensions.5122ed46) is not possible if the user entered as "SiteOwnerLogin" does not have an email adress. Is there any workaround for this?

The user has been synced by local active directory.

#### Observed Behavior
The tenant.CreateSiteCollection throws the following exception:

Exception occurred: user_email@domain.com is not a valid user.

   _at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)
   at Microsoft.SharePoint.Client.TenantExtensions.CreateSiteCollection(Tenant tenant, SiteEntity properties, Boolean removeFromRecycleBin, Boolean wait, Func`2 timeoutFunction)_

#### Steps to Reproduce

1. Create a user in user profile service without an email adress. 
2. Enter the user loginname as SiteOwnerLogin in code below.
3. Create a new console application.
4. Add PNP Core Package from Nuget to the project.
5. Add the code below to the project, enter valid data for the username and the urls and and execute it.

```
//enter the username of a user without an email adress
string userWithOutEmail = "userWithOutEmail@mytesttenant.onmicrosoft.com";
//enter a valid tenant admin url
string tenantAdminUrl = "https://mytesttenant-admin.sharepoint.com";
//enter a valid tenant url
string tenantUrl = "https://mytesttenant.sharepoint.com";
string newSiteTitle = "AdminWithOutEmailTest";

using (var tenantContext = new ClientContext ()) {
     var tenant = new Microsoft.Online.SharePoint.TenantAdministration.Tenant (tenantContext);

     var properties = new SiteEntity {
         Url = $"{tenantUrl}/Sites/{newSiteTitle}",
         Title = newSiteTitle,
         SiteOwnerLogin = userWithOutEmail,
         Template = "STS#0",
         Lcid = (uint) 1033,
         Description = newSiteTitle,
         StorageMaximumLevel = 10240L,
         StorageWarningLevel = 8192L
     };

     var SiteId = tenant.CreateSiteCollection (properties, false, true, message => {
         return false;
     });
 }
```

**Comment by MrTantum** [comment]
Seems to have been a temporary issue. It's working on our tenant now even for the users without mail.

Therefore I'll close the topic.
