### ISSUE TITLE
Cannot enable custom feature on site (Spfx extension package)

### ISSUE THREAD

**Issue by guillaume-kizilian** [SharePoint/PnP-Sites-Core#1693]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Upon using Provisioning Template (<Feature>) or Powershell Cmdlet (Enable-PnPFeature), custom feature (Spfx extension) should get enabled on site.

#### Observed Behavior
The feature is not enabled (from provisioning template log, its not even found). However it's found/possible to disable it, if the feature is enabled.

#### Steps to Reproduce
- Upload a spfx package containing a feature with an AppCustomizer to your AppCatalog with SkipFeatureDeployement to false. 
- Add the application to your Site.
- Connect to your site with PnP Cmdlet (Connect-PnPOnline -Url <yoursite>)
- List all Features (Get-PnPFeature)
- Disable it (Disable-PnPFeature -Identity <yourfeatureid>)
- List all Features (Get-PnPFeature)
- Enable it (Enable-PnPFeature -Identity <yourfeatureid>)

![test](https://user-images.githubusercontent.com/6792560/38031033-92ec295a-329a-11e8-9d00-d4d5858e6831.jpg)

#### Submission Guidelines
- The same behaviour happens with PnP Provisionning Template (I've tried both Web and Site Feature)
`<?xml version="1.0" encoding="utf-8" ?>
<pnp:ProvisioningTemplate ID="Site_local" Version="1" 
  xmlns:pnp="http://schemas.dev.office.com/PnP/2018/01/ProvisioningSchema">
  <pnp:Features>
    <pnp:WebFeatures>
      <pnp:Feature ID="f08ee3fe-f6de-44dc-9914-fdd703e87193" Deactivate="false"/>
    </pnp:WebFeatures>
  </pnp:Features>
</pnp:ProvisioningTemplate>`

- The following error appears when lauching PnPProvisionning Template with trace : 

> SitesProvisioning.exe Information: 0 : 2018-03-28 14:58:45.0883	[OfficeDevPnP.Core]	[0]	[Information]	Error caught while waiting for ExecuteQueryRetry to complete. Error = Microsoft.SharePoint.Client.ServerException: Feature with Id 'f08ee3fe-f6de-44dc-9914-fdd703e87193' is not installed in this farm, and cannot be added to this scope.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.FeatureExtensions.ProcessFeatureInternal(FeatureCollection features, Guid featureID, Boolean activate, FeatureDefinitionScope scope, Int32 pollingIntervalSeconds).	0ms	

There might be another method to use to get all the available features, because the one it use only brings the ones that are enabled.

- Using SharePointPnPCoreOnline v.2.24.1803 and v2.22.1801

Best Regards.

**Comment by qazqwertish** [comment]
Any answer on this one? We are having the same issue.
