### ISSUE TITLE
ApplyWebTemplate() is not working - 10|13-Web API Permissions Error occurred while applying the template :Microsoft.SharePoint.Client.ServerException: Insufficient privileges to complete the operation

### ISSUE THREAD

**Issue by gboraiah** [SharePoint/PnP-Sites-Core#1749]
I have created a solution to provision the modern site programetically. 
Am able to get the template : 
Trying connection to the source site...
Connection to the source site successful...
1|17-Regional Settings
2|17-Supported UI Languages
3|17-Audit Settings
4|17-Site Security
5|17-Fields (Export step)
6|17-Content Types (Export step)
7|17-List instances (Export step)
8|17-Features
9|17-Page Contents
10|17-Client Side Page Contents
11|17-Property bag entries
12|17-Workflows
13|17-Web Settings
14|17-Navigation
15|17-Image Renditions
16|17-Localization
17|17-Application Lifecycle Management
Reading the template is successful...

But when i try applying the template it fails  with the below error: 
Started applying the template
1|13-Initializing engine
2|13-Regional Settings
3|13-Site Security
4|13-Features
5|13-List instances (ListAndStandardFields step)
6|13-List instances (LookupFields step)
7|13-List instances (ListSettings step)
8|13-Tenant Settings
9|13-Application Lifecycle Management
10|13-Web API Permissions
Error occurred while applying the template :Microsoft.SharePoint.Client.ServerException: Insufficient privileges to complete the operation.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectWebApiPermissions.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo)
   at SPOnline.SiteProvisioningTool.ProvisioningEngine.ModernSiteProvisioningEngine.ApplyWebTemplate() in D:\Krish\SourceTFS\EATON\EatonSiteProvisioningUtility\SPOnline.SiteProvisioningTool\ProvisioningEngine\ModernSiteProvisioningEngine.cs:line 171

I have attached the Template XML file for your reference.
[ERGSite.txt](https://github.com/SharePoint/PnP-Sites-Core/files/1991486/ERGSite.txt)

Am using the following packages in the project:
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AngleSharp" version="0.9.9.1" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.Azure.ActiveDirectory.GraphClient" version="2.1.1" targetFramework="net452" />
  <package id="Microsoft.Azure.KeyVault.Core" version="2.0.4" targetFramework="net452" />
  <package id="Microsoft.Data.Edm" version="5.8.3" targetFramework="net452" />
  <package id="Microsoft.Data.OData" version="5.8.3" targetFramework="net452" />
  <package id="Microsoft.Data.Services.Client" version="5.8.3" targetFramework="net452" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="1.0.0" targetFramework="net452" />
  <package id="Microsoft.Extensions.Options" version="1.0.0" targetFramework="net452" />
  <package id="Microsoft.Extensions.Primitives" version="1.0.0" targetFramework="net452" />
  <package id="Microsoft.Extensions.WebEncoders" version="1.0.0" targetFramework="net452" />
  <package id="Microsoft.Graph" version="1.3.0" targetFramework="net452" />
  <package id="Microsoft.Graph.Core" version="1.8.1" targetFramework="net452" />
  <package id="Microsoft.IdentityModel" version="6.1.7600.16394" targetFramework="net452" />
  <package id="Microsoft.IdentityModel.Clients.ActiveDirectory" version="3.19.1" targetFramework="net452" />
  <package id="Microsoft.SharePointOnline.CSOM" version="16.1.7618.1200" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="11.0.2" targetFramework="net452" />
  <package id="SharePointPnP.IdentityModel.Extensions" version="1.2.3" targetFramework="net452" />
  <package id="SharePointPnPCoreOnline" version="2.26.1805" targetFramework="net452" />
  <package id="System.ComponentModel" version="4.3.0" targetFramework="net452" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="net452" />
  <package id="System.Globalization" version="4.3.0" targetFramework="net452" />
  <package id="System.IdentityModel.Tokens.Jwt" version="4.0.0" targetFramework="net452" />
  <package id="System.Linq" version="4.3.0" targetFramework="net452" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="net452" />
  <package id="System.Net.Http" version="4.3.3" targetFramework="net452" />
  <package id="System.Reflection" version="4.3.0" targetFramework="net452" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="net452" />
  <package id="System.Runtime" version="4.3.0" targetFramework="net452" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="net452" />
  <package id="System.Spatial" version="5.8.3" targetFramework="net452" />
  <package id="System.Text.Encodings.Web" version="4.4.0" targetFramework="net452" />
  <package id="System.Threading" version="4.3.0" targetFramework="net452" />
  <package id="WindowsAzure.Storage" version="8.7.0" targetFramework="net452" />
</packages>

**Comment by erwinvanhunen** [comment]
Are you running the engine as a tenant admin? That is a level of access required in order to approve webapi permissions.

**Comment by erwinvanhunen** [comment]
I just merged a fixed for this issue: PR #1752

**Comment by gboraiah** [comment]
The credentials am using to do the provisioning is a SharePoint administrator. Still i get this error
10|13-Web API Permissions
Error occurred while applying the template :Microsoft.SharePoint.Client.ServerException: Insufficient privileges to complete the operation.
