### ISSUE TITLE
List and site Lookup fields no longer working

### ISSUE THREAD

**Issue by waaromikniet** [SharePoint/PnP-Sites-Core#1812]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[x] SharePoint 2016
[x] SharePoint 2013

#### Expected or Desired Behavior
In my template I have a list lookup field like below. I expect this to be provisioned. This works with the January 2018 release.

`            <Field ID="{fa564e0f-0c70-4ab9-b863-0177e6ddd247}" Name="Title" Required="true" Indexed="TRUE" EnforceUniqueValues="TRUE" Type="Text" StaticName="Title"/>
            <Field Type="Lookup" List="Lists/DocumentExchangeLibrary" Name="DocumentProcessStatus" StaticName="DocumentProcessStatus" DisplayName="Document Process Status" Group="DCP" ShowField="CalStatus" Indexed="TRUE" Hidden="TRUE" Viewable="FALSE" ID="{7f5ad3ab-94dc-4999-8f03-7d5a701c8c49}"/>`

#### Observed Behavior
The above field XML is no longer working. It seems that the attribute List="Lists/DocumentExchangeLibrary"  is no longer working with the May release.

#### Steps to Reproduce

This field XML does not work

`            <Field ID="{fa564e0f-0c70-4ab9-b863-0177e6ddd247}" Name="Title" Required="true" Indexed="TRUE" EnforceUniqueValues="TRUE" Type="Text" StaticName="Title"/>
            <Field Type="Lookup" List="Lists/DocumentExchangeLibrary" Name="DocumentProcessStatus" StaticName="DocumentProcessStatus" DisplayName="Document Process Status" Group="DCP" ShowField="CalStatus" Indexed="TRUE" Hidden="TRUE" Viewable="FALSE" ID="{7f5ad3ab-94dc-4999-8f03-7d5a701c8c49}"/>`

When changing List="Lists/DocumentExchangeLibrary" to List="{listid:Document Exchange Library}" WebId="{siteid}"

my template does work. Is  List="Lists/DocumentExchangeLibrary"  no longer supported?

**Comment by waaromikniet** [comment]
#1786 # #1791

**Comment by ezybzy** [comment]
For me, it fails with the following field schema.
`<Field DisplayName="Parent" Description="Parent Menu" Name="Parent" ID="{f09f3440-9375-4ae0-a836-f31ca2ce0477}" Type="Lookup" EnableLookup="TRUE" List="Self" ShowField="Title" SourceID="{{listid:My Menu}}" StaticName="Parent" ColName="int1" RowOrdinal="0" />`

The exception shown is
`The property or field 'ServerRelativeUrl' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.
   at Microsoft.SharePoint.Client.ClientObject.CheckUninitializedProperty(String propName)
   at Microsoft.SharePoint.Client.Web.get_ServerRelativeUrl()
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.FieldUtilities.FixLookupField(String fieldXml, Web web)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.CreateField(XElement fieldElement, ListInfo listInfo, TokenParser parser, String originalFieldXml, ClientContext context, PnPMonitoredScope scope)`
...

When I look at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.FieldUtilities.FixLookupField, it seems that it fails because
`var targetList = web.GetList($"{web.ServerRelativeUrl.TrimEnd('/')}/{listAttr}");`
doesn't work at **web.ServerRelativeUrl** .
