### ISSUE TITLE
Apply-PnPProvisioningTemplate error: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: Only one usage of each socket address (protocol/network address/port) is normally permitted 123.45.678.901:443

### ISSUE THREAD

**Issue by khha** [SharePoint/PnP-Sites-Core#1874]
#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
15.0.4569.1506

#### Expected or Desired Behavior
Files and folders need to be provisioned to some sitecollection

#### Observed Behavior
When I start the "Apply-PnPProvisioningTemplate" command, it provisioning allot of files. And somewhere in the middle of provisioning these files I receive this error:

PowerShell_ISE.exe Error: 0 : 2018-08-13 11:06:25.5676	[OfficeDevPnP.Core]	[0]	[Error]	ExecuteQuery threw following exception: System.Net.WebException: Unable to connect to the remote server 
---> System.Net.Sockets.SocketException: Only one usage of each socket address (protocol/network address/port) is normally permitted 172.21.179.113:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Excep
tion& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.Execute()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent).	0ms	
PowerShell_ISE.exe Information: 0 : 2018-08-13 11:06:25.5832	[Files]	[10]	[Debug]	Code execution scope ended	30154ms	493d3b5d-7f8e-4806-98e3-8c234270a017
PowerShell_ISE.exe Information: 0 : 2018-08-13 11:06:25.5832	[Provisioning]	[10]	[Debug]	Code execution scope ended	31621ms	493d3b5d-7f8e-4806-98e3-8c234270a017
Apply-PnPProvisioningTemplate : The running command stopped because the user selected the Stop option.

#### Steps to Reproduce
Create a new pnp template where you are trying to provisioning files and folders with allot of files. Start the "Apply-PnPProvisioningTemplate" command.

ps. I googled for this error and found some workaround to increase the MaxUserPort key in the registry.

**Comment by junian** [comment]
Recently I also had this similar issue with multiple `ExecuteQuery`.
Changing `MaxUserPort` worked only for a couple of days. I haven't try `TcpTimedWaitDelay`, I was afraid it'll messing up the server.

But I have an idea by using try catch like this:

```csharp
try
{
    using (var ctx = clientContext.Clone(clientContext.Url))
    {
        // Put your code HERE

        ctx.ExecuteQueryRetry();
    }
    return;
}
catch (Exception ex)
{
    if (ex is WebException webex
        && webex.InnerException is SocketException sockex
        && sockex?.SocketErrorCode == SocketError.AddressAlreadyInUse)
    {
        // Do something when `AddressAlreadyInUse` caught.
        // For example, retry above process
    }
    else
    {
        // Forward exception if it's not `AddressAlreadyInUse`
        throw;
    }
}
```

I wrote a [blog post](https://www.junian.net/sharepoint-clientcontext-socket-exception/) for more detailed information in case anyone else faced similar issue in the future.
