### ISSUE TITLE
"Could not get algorithm from X509AsymmetricSecurityKey" on Framework 4.7 when using S2S

### ISSUE THREAD

**Issue by OleAlbers** [SharePoint/PnP-Sites-Core#1997]
#### Category
[X] Bug

#### Environment
[X] SharePoint 2013

#### Expected or Desired Behavior
Connect to SharePoint using S2S,  using Windows Identity

#### Observed Behavior
When changing the project to .NET Framework 4.7.2, the Creation of the IssueToken throws the following error:
```
System.InvalidOperationException: Could not get algorithm from X509AsymmetricSecurityKey
at Microsoft.IdentityModel.S2S.Tokens.X509AsymmetricSignatureProvider..ctor(X509AsymmetricSecurityKey x509Key)
   at Microsoft.IdentityModel.S2S.Tokens.SignatureProvider.Create(SigningCredentials signingCredentials)
   at Microsoft.IdentityModel.S2S.Tokens.JsonWebSecurityTokenHandler.Sign(String signingInput, SigningCredentials signingCredentials)
   at Microsoft.IdentityModel.S2S.Tokens.JsonWebSecurityTokenHandler.WriteTokenAsString(SecurityToken token)
   at myproject.TokenHelper.IssueToken(String sourceApplication, String issuerApplication, String sourceRealm, String targetApplication, String targetRealm, String targetApplicationHostName, Boolean trustedForDelegation, IEnumerable`1 claims, Boolean appOnly) in C:\myproject\TokenHelper.cs:line 881
 ```` 
The Error is thrown from the `IssueToken()` - Method from the TokenHelper called by `GetS2SAccessTokenWithClaims()` 

my code calling that method:  'var accessToken = TokenHelper.GetS2SAccessTokenWithWindowsIdentity(siteUri, null);' (where siteUri is the SharePoint - URL obiously)

#### Steps to Reproduce
- Use `GetS2SAccessTokenWithWindowsIdentity()` on Framework 4.6.1 (or lower). Have a working connection to be sure no configuration issue exists.->No Error
- Change the Framework to 4.7.2.
- Run the program again -> Error

**Comment by lafe** [comment]
Should be the issue fixed in https://github.com/SharePoint/PnP-IdentityModel/pull/1. Unfortunately, there is no activity from Microsoft or the PnP team regarding the PR.

**Comment by OleAlbers** [comment]
Updating PnP/CSOM still leads to the same problem, but the following helped:
<system.web>
    <compilation debug="true" targetFramework="4.7.2"/>
    <httpRuntimetargetFramework="4.6.2"/>
</system.web>

(The magic lies in httpRuntimetargetFramework)
