### ISSUE TITLE
Provisioning fails when Installing apps in sitecollection

### ISSUE THREAD

**Issue by SimSpfx** [SharePoint/PnP-Sites-Core#2102]
#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Observed Behavior

When provisioning a pnp template the process fails on the application lifecycle management part.
      <pnp:ApplicationLifecycleManagement>
        <pnp:Apps>
          <pnp:App AppId="825a2904-167d-41f1-b859-912214c97165" Action="Install" />
          <pnp:App AppId="05a081cc-8120-4d21-8941-e3b9188b1f4d" Action="Install" />
          <pnp:App AppId="6dddc5f7-33e5-4749-bae3-2feb8a34755d" Action="Install" />
        </pnp:Apps>
      </pnp:ApplicationLifecycleManagement>

This used to work like one week ago. We did not update code or template. 
We use c sharp to create and apply the template. I removed the part from the xml and reverted back to a small code example and this works fine.
For example:
![image](https://user-images.githubusercontent.com/47321821/54205606-f4aa4380-44d6-11e9-91b9-984a117bcdaa.png)

The error itself:

12/14 - Application Lifecycle Management
!X! {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Exception of type 'Microsoft.SharePoint.Client.ResourceNotFoundException' was thrown."}}}

#### Steps to Reproduce

1) install an app in your tenant app catalog
2) Get the guid(App id)
3) Create a simple xml scheme with only app lifecycle management in
4) try to provision on an existing site collection.

Any pointers would be very nice. 

Kind regards
Simon

**Comment by jansenbe** [comment]
Does this still repro?

**Comment by SimSpfx** [comment]
Stil does. I am using version 3.7.1903 

Fetching the template
Provisioning...
01/04 - Initializing engine
02/04 - Regional Settings
03/04 - Application Lifecycle Management
!X! {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Exception of type 'Microsoft.SharePoint.Client.ResourceNotFoundException' was thrown."}}}
Departement provisioning failed
-------------------------------------------------

**Comment by fredupstair** [comment]
Same problem and same conditions.

`2019-03-22T03:23:56.515 [Info] 12/15 - Application Lifecycle Management
2019-03-22T03:23:57.952 [Error] error message: {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"it-IT","value":"Exception of type 'Microsoft.SharePoint.Client.ResourceNotFoundException' was thrown."}}} - stack trace:    at OfficeDevPnP.Core.ALM.AppManager.<BaseRequest>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OfficeDevPnP.Core.ALM.AppManager.<InstallAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OfficeDevPnP.Core.ALM.AppManager.Install(Guid id, AppCatalogScope scope)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectApplicationLifecycleManagement.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser)
   at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)
   at Hera.Provisioning.Helpers.SharepointHelper.<ApplyProvisioningTemplate>d__2.MoveNext()
`

**Comment by jonathanhotono** [comment]
I'm also getting this on 3.7.1903
I have never been able to use this feature even on the previous versions and always throws this error.
![image](https://user-images.githubusercontent.com/6864547/55377637-0c0da700-5540-11e9-9d9d-fd1e7b5edf60.png)

**Comment by abhishekbhatore** [comment]
What was the solution for this problem ?

**Comment by SimSpfx** [comment]
You can use code to install the apps at this moment. You can find an example above. I guess they are working on it. I will test if the new release fixed anything.

**Comment by wardm95** [comment]
Issue still exists on 3.11.1907.
