### ISSUE TITLE
Get-PnPTenantSite throws error

### ISSUE THREAD

**Issue by LouFarho** [SharePoint/PnP-Sites-Core#2103]
#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Command should return site or sites
Please note Get-SPOSite throws similar error

#### Observed Behavior
Get-PnPTenantSite -Detailed
Get-PnPTenantSite : The type of data at position 1678 is different than the one expected.
At line:1 char:1
+ Get-PnPTenantSite -Detailed
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPTenantSite], InvalidOperationException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.GetTenantSite

#### Steps to Reproduce
Execute command
Get-PnPTenantSite -Detailed

Thanks for your contribution! Sharing is caring.

**Comment by mdissel** [comment]
See #2104

**Comment by jimmywim** [comment]
Reproduced with PnP PowerShell: 3.6.1902.2

```
Message          : The type of data at position 1661 is different than the one expected.
Stacktrace       :    at Microsoft.SharePoint.Client.JsonReader.ReadGuid()
                      at
                   Microsoft.Online.SharePoint.TenantAdministration.SiteProperties.InitOnePropertyFromJson(String
                   peekedName, JsonReader reader)
                      at Microsoft.SharePoint.Client.ClientObject.FromJson(JsonReader reader)
                      at Microsoft.SharePoint.Client.JsonReader.ReadJsonObject(Type fallbackType)
                      at Microsoft.SharePoint.Client.JsonReader.ReadObjectArray(Type fallbackElementType)
                      at Microsoft.SharePoint.Client.ClientObjectCollection.InitOnePropertyFromJson(String peekedName,
                   JsonReader reader)
                      at Microsoft.Online.SharePoint.TenantAdministration.SPOSitePropertiesEnumerable.InitOnePropertyFr
                   omJson(String peekedName, JsonReader reader)
                      at Microsoft.SharePoint.Client.ClientObject.FromJson(JsonReader reader)
                      at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
                      at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
                      at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at
                   Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext
                   clientContext, Int32 retryCount, Int32 delay, String userAgent)
                      at SharePointPnP.PowerShell.Commands.GetTenantSite.ExecuteCmdlet()
                      at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()
ScriptLineNumber : 1
```

**Comment by jimmywim** [comment]
Root cause investigation: https://github.com/SharePoint/sp-dev-docs/issues/3577
