### ISSUE TITLE
Get-PnPProvisioningTemplate : The type of data at position 1144 is different than the one expected

### ISSUE THREAD

**Issue by JoaoAlmeidaPoa** [SharePoint/PnP-Sites-Core#2104]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Brief Description
I discover that problem below, only occurs when I try to export Handlers Lists, if I ran with other Handlers except Lists, this code works fine, but when I include the Handler lists I has the problem below.

#### Steps to Reproduce
$userLogin = "xxxx@xxxx.onmicrosoft.com"
$cred = Get-Credential -UserName $userLogin -Message "Login PNP"

$WebURL = "https://xxxx.sharepoint.com/sites/xxx/"
Connect-PnPOnline -Url $WebURL -Credentials $cred
Get-PnPContext
$teamSiteUrl = New-PnPWeb -Title "Projeto 06" -Url "projeto06" -Description "Projeto 05" -Locale 1046 -Template "STS#3" -ErrorAction Stop

Connect-PnPOnline -Url $teamSiteUrl.Url -Credentials $cred
Get-PnPContext

Get-PnPProvisioningTemplate -Out "C:\scripts\template-demo13-projeto06.xml" -Handlers "Lists" -ExcludeHandlers "SiteSecurity,TermGroups,Fields,ContentTypes,Navigation" -Force

#### Expected Behavior
Create a XML file with the template of site

#### Get-PnpException

Message          : The type of data at position 1145 is different than the one expected.
Stacktrace       :    at Microsoft.SharePoint.Client.JsonReader.ReadGuid()
                      at Microsoft.SharePoint.Client.Site.InitOnePropertyFromJson(String peekedName, JsonReader reader)
                      at Microsoft.SharePoint.Client.ClientObject.FromJson(JsonReader reader)
                      at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
                      at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
                      at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)
                      at Microsoft.SharePoint.Client.ClientContextExtensions.GetSiteCollectionContext(ClientRuntimeContext clientContext)
                      at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ExtractFields(Web web, List siteList, List`1 contentTypeFields, ListInstance list, List`1 lists, 
                   ProvisioningTemplateCreationInformation creationInfo, ProvisioningTemplate template)
                      at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ExtractObjects(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation 
                   creationInfo)
                      at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
                      at SharePointPnP.PowerShell.Commands.Provisioning.Site.GetProvisioningTemplate.ExtractTemplate(XMLPnPSchemaVersion schema, String path, String packageName)
                      at SharePointPnP.PowerShell.Commands.Provisioning.Site.GetProvisioningTemplate.ExecuteCmdlet()
                      at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()
ScriptLineNumber : 1

**Comment by mdissel** [comment]
I can relate this back to the "SensitivityLabel":null .. In tenants with library version 1213/1214 a null is returned, but the the property SensitivityLabel is a Guid (non-nullable) type
On tenants with a server library version 1224 "SensitivityLabel":"\/Guid(00000000-0000-0000-0000-000000000000)\/" is returned..

I have no idea how to solve this.

**Comment by metalogique** [comment]
I have the same issue in 2 of my tenants when deploying page layouts in a classic publishing site using PnpPowershell.
The underlying issue is commented on by @VesaJuvonen here https://github.com/SharePoint/sp-dev-docs/issues/3577#issuecomment-472160143

**Comment by jansenbe** [comment]
Issue is fixed server-side, closing this now
