### ISSUE TITLE
GetProvisioningTemplate throws Could not convert string to integer: undefined. Path 'emphasis.zoneEmphasis'

### ISSUE THREAD

**Issue by statto1974** [SharePoint/PnP-Sites-Core#2316]
#### Category
[ *] Bug
[ ] Enhancement

#### Environment
[ *] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior

Calling GetProvisioningTemplate should complete successfully and return a Template object

#### Observed Behavior

GetProvisioningTemplate  works successfully if IncludeAllClientSidePages is set to false

#### Steps to Reproduce

The following code produced the error

```
using (var context = manager.GetSharePointOnlineAuthenticatedContextTenant(siteUrl, "user", "password"))
            {
                var ptci = new ProvisioningTemplateCreationInformation(context.Web)
                {
                    FileConnector = new FileSystemConnector(@"C:\scripts\mb\provisioning", ""),
                    IncludeAllClientSidePages = true,
                    HandlersToProcess = Handlers.Pages | Handlers.PageContents,

                    ProgressDelegate = delegate (String message, Int32 progress, Int32 total)
                    {

                    Console.WriteLine("{0:00}/{1:00} - {2}", progress, total, message);
                    }
                };

                // Execute actual extraction of the tepmplate
                template = context.Web.GetProvisioningTemplate(ptci);

            }
```

Exception Stack

Newtonsoft.Json.JsonReaderException
  HResult=0x80131500
  Message=Could not convert string to integer: undefined. Path 'emphasis.zoneEmphasis', line 1, position 210.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.JsonReader.ReadInt32String(String s)
   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at OfficeDevPnP.Core.Pages.CanvasControl.GetType(String controlDataJson)
   at OfficeDevPnP.Core.Pages.ClientSidePage.LoadFromHtml(String html, String pageHeaderHtml)
   at OfficeDevPnP.Core.Pages.ClientSidePage.Load(ClientContext cc, String pageName)
   at Microsoft.SharePoint.Client.PageExtensions.LoadClientSidePage(Web web, String pageName)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.ClientSidePageContentsHelper.ExtractClientSidePage(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo, PnPMonitoredScope scope, String pageUrl, String pageName, Boolean isHomePage, Boolean isTemplate)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectClientSidePageContents.ExtractObjects(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
   at Microsoft.SharePoint.Client.WebExtensions.GetProvisioningTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\toby\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 40

#### Submission Guidelines
_Delete this section after reading_
- All suggestions or bugs are welcome, please let us know what's on your mind.
- If you are reporting any issues around PnP Core Component, please reproduce the issue with latest release.
- If you are reporting issue around PnP Provisioning Engine, please share the xml template, if possible.
- If you are reporting an issue around any of the samples, please ensure that you have clear reference on the sample and possibly code file, which should be fixed.
- If you have a general question, please use the [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community.
- Remember to include sufficient details and context.
- If you have multiple suggestions or bugs please submit them in seperate bugs so we can track resolution.

Thanks for your contribution! Sharing is caring.

**Comment by mmohamedbasith** [comment]
I was able to replicate the issue when IncludeAllClientSidePages = true . I updated all my packages to the latest stable version . Its started working.

**Comment by NicolajHedeager** [comment]
I guess the PR #2318 will solve this issue.

**Comment by jansenbe** [comment]
Did you create the page by starting from one of the OOB page templates?

**Comment by jansenbe** [comment]
This should be fixed with the October release. If not please create a new issue
