### ISSUE TITLE
Sharepoint Online Provisioning Issue

### ISSUE THREAD

**Issue by rathnamvemula** [SharePoint/PnP-Sites-Core#2382]
Hi,
We are using PnP vesion (2.11.1701.1) to provision the SharePoint sites, which is working fine from the past 2+ years. All of a sudden, the sites started failing provisioning with the following error.

`Error from Logs:

> 2019-03-14 16:04:56.4880	[Pims]	[0]	[Information]	Site collection creation is still in Progress	0ms	
2019-03-14 16:05:26.8964	[Pims]	[0]	[Information]	Site collection creation is still in Progress	0ms	
2019-03-14 16:05:57.3837	[Pims]	[0]	[Information]	Site collection creation is still in Progress	0ms	
2019-03-14 16:06:27.7874	[Pims]	[0]	[Information]	Site collection creation is still in Progress	0ms	
2019-03-14 16:06:27.7874	[Pims]	[0]	[Information]	Cancelling the Wait loop	0ms	
2019-03-14 16:06:28.8858	[Pims - CreateSiteCollection]	[0]	[Error]	   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)
   at Provisioning.Infrastructure.Jobs.Handlers.SiteCollectionProvisioningJobHandler.CreateSiteCollection(SiteCollectionProvisioningJob job)	0ms`

**Here is the code, which is failing. We increased the time out from 30 min to 60 min, 120 mins, but the site provisioning is still failing.**

`tenant.CreateSiteCollection(newSite, true, true, timeoutFunction: (operationMessage) =>
                        {

                            if (operationMessage == TenantOperationMessage.CreatingSiteCollection)
                            {
                                Log.Info(Constants.LOGGING_SOURCE, "Site collection creation is still in Progress");
                            }
                            if (watch.Elapsed.TotalMinutes > 30)
                            {
                                Log.Info(Constants.LOGGING_SOURCE, "Cancelling the Wait loop");
                                watch.Stop();
                                return true;// set to true to cancel the wait loop
                            }
                            else
                                return false;
                        });`

Appreciate, if someone can help on this issue. Thanks in Advance.

**Comment by fzbm** [comment]
Same issue here on one tenant. We are currently unable to create site collections (STS#0) due to the fact, that the operation never completes.
