### ISSUE TITLE
ListItemAllFields generates an error when trying to update document fields for libraries in Romanian

### ISSUE THREAD

**Issue by ioancrisan** [SharePoint/PnP-Sites-Core#2449]
#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
`ListItemAllFields` can be used to update the custom document fields in a list when the site language is set to Romanian.

#### Observed Behavior
```C#
        var fileInformation = new FileCreationInformation
        {
            Url = $"{folder.ServerRelativeUrl}/file.docx",
            Overwrite = true,
            Content = new byte[3] {1, 2, 3},
        };
        var file = folder.Files.Add(fileInformation);
        await this.clientContext.ExecuteQueryAsync().ConfigureAwait(false);

        this.clientContext.Load(file);
        await this.clientContext.ExecuteQueryAsync().ConfigureAwait(false);

        var listItemFields = file.ListItemAllFields;
        listItemFields["SyncTool"] = "my tool";
        listItemFields["SyncId"] = Guid.NewGuid().ToString();
        listItemFields["OriginalName"] = "Mydoc.docx";
        listItemFields.Update();

        await this.clientContext.ExecuteQueryAsync().ConfigureAwait(false);
```

The code above throws an exception on the last line (see below). When running the same code against a SharePoint site configured for the English language, everything works fine.

#### Steps to Reproduce
* Add a reference to SharePointPnPCoreOnline to the project.
```
        <PackageReference Include="SharePointPnPCoreOnline" Version="3.14.1910" />
```
* Execute the code above with proper site configuration.
* The last line will throw an exception:

```
Microsoft.SharePoint.Client.ServerException: Imposibil de invocat metoda sau de regăsit proprietatea din obiectul null. Obiectul returnat de următoarea stivă de apelare este null. "ListItemAllFields
"
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Kephas.Threading.Tasks.ThreadContextAwaiter.GetResult()
   at Kephas.SharePoint.UploaderService.<CreateFileAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Kephas.Threading.Tasks.ThreadContextAwaiter`1.GetResult()
   at Kephas.SharePoint.UploaderService.<>c__DisplayClass13_0.<<UploadDocumentCoreAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Kephas.Threading.Tasks.ThreadContextAwaiter.GetResult()
   at Kephas.Diagnostics.Profiler.<WithStopwatchAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Kephas.Threading.Tasks.ThreadContextAwaiter`1.GetResult()
   at Kephas.SharePoint.UploaderService.<UploadDocumentCoreAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Kephas.Threading.Tasks.ThreadContextAwaiter.GetResult()
   at Kephas.SharePoint.UploaderService.<UploadDocumentAsync>d__11.MoveNext()
```

**Comment by ioancrisan** [comment]
After some more digging here is more information:
* I noticed that the first part, adding the file, _seems_ to be successful. I do not get any errors and, in debug mode, when the second part/fields updating crashes with the above error and I am in break mode, I can use the file link to access the file and download it. However:
  * The UI does not display the file at all, as if it wasn't there.
  * After a while, accessing the direct file link gives me a 404 - Not Found.
* I get a correlation ID for querying the server log. However, I didn't find a way to access it.
Any thoughts?

**Comment by cmzaragoza** [comment]
Hi @ioancrisan. I've tried to reproduce your issue, but I couldn't. I've created a Communication demo site in German, and your code is working perfectly fine for me. Regarding your notes above, I think is normal if the UI is not able to  display the file, as the file itself is kind of "corrupted", because the content is just a random-demo one.

**Comment by cmzaragoza** [comment]
Hi @ioancrisan. I totally agree. May I suggest you close this issue and create a new one requesting that? Cheers.
