### ISSUE TITLE
Operation is not valid due to the current state of the object while applying template

### ISSUE THREAD

**Issue by Kerokk** [SharePoint/PnP-Sites-Core#2451]
Which PnP repository should you use to report the issue? 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[x] Bug

#### Environment
[x] Office 365 / SharePoint Online

PnP version: 3.13.1909.0

#### Expected or Desired Behavior
To be able to apply a provisioning template to a newly created site.

#### Observed Behavior
When trying to apply a provisioning template to a newly created site we're getting the following exception:

`Operation is not valid due to the current state of the object.    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectWorkflows.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser)
   at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)
   at PnpProvisioning.PnpMethods.ApplyProvisioning(String url, String listId, Guid projectGuid, String projectid) in \PnpMethods.cs:line 1111
   at PnpProvisioning.PnpMethods.ProvisionSite(String url, String owner, String title, String description, String listId, String status, String projectId, TextWriter log) in\PnpMethods.cs:line 517`

This issue started happening every so often after 9/25/19 and the solution was always to give it a few hours, and it would start working again.  Then on (Friday) 10/4/19 we received the exception, gave it the weekend, and tried again on (Monday) 10/7/19 but still got the same exception.

So on (Friday) (10/11/19) we updated the PnP Nuget package in our solution from 3.4.1812.2 to 3.13.1909.0.  After redeploying in our test (first release) tenant the solution was able to create a site and apply the template, but when we redeployed into our production tenant we still received the same exception.  We figured something was probably fixed on MS's end, so we gave it the weekend to propagate to our production tenant.

This morning (10/14/19) I tried to create another site in both our test and production tenants and both worked.  So I tried to create another in production and that one worked as well, but after creating a 3rd site, it began to fail again (throwing the same exception).  So I checked our test tenant to see if it was failing there as well, but the process continued to work.

**Comment by Kerokk** [comment]
It started to work again this afternoon.  From what I can tell it was an issue with a Microsoft service in our tenant, but really have no way to verify.

The last time we got it to fail today (10/18/19) we were running the code locally (instead of from the web service) and set it to break on Common Language Runtime Exceptions.  When the provisioning template was applying, we got an exception while it was creating one of the libraries saying "Exception from HRESULT: 0x80131904" with a ServerErrorCode of -2146232060.  Looking around online for that, it seems most things were pointing to an issue with SQL.  So I wanted to get it to error out one more time near the same spot before submitting a ticket with Microsoft, but the solution has been working ever since.  

I should add that, yesterday (10/17/19), our users were reporting slow loading times in O365.  So we submitted a MS ticket for that, and received a response from support this morning (10/18/19) saying they've engaged their back-end team to look into the issue.  About an hour after that response we no longer had any issues applying a template to a newly created site.
