### ISSUE TITLE
401 Unauthorized when executing AddAdministrators

### ISSUE THREAD

**Issue by EagleWizard28** [SharePoint/PnP-Sites-Core#2494]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Adding the user as site admin in a consistent way.

#### Observed Behavior
When executing the method, in 10% of the cases I get a 401 Unauthorized
The site collection admin in the admin portal is then set to "System Account"
```
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.<ExecuteAsync>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<GetFormDigestInfoPrivateAsync>d__b.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<EnsureFormDigestAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)
   at Microsoft.SharePoint.Client.SecurityExtensions.AddAdministrators(Web web, List`1 adminLogins, Boolean addToOwnersGroup)
```

#### Steps to Reproduce
Create a new site collection using a tenantContext which is created using a username password combination

```
var tenant = new Tenant(tenantContext);
            tenant.CreateSiteCollection(newSiteCollectionUrl, siteData.SiteName,
                SharePointSettings.ServiceUserName, "STS#3", 25600000, 25500000, 3, 0, 0, siteData.Lcid, true);

```

Then afterwards try to add an administrator with the "AddAdministrators" function

**Comment by gautamdsheth** [comment]
Not exactly sure why this is happening, but can you try it in a different way as mentioned below:

```csharp
TeamNoGroupSiteCollectionCreationInformation tngci = new TeamNoGroupSiteCollectionCreationInformation()
{
	Title = "New STS3 site",
	Url = "https://tenant.sharepoint.com/sites/TestSite",
	Description = "test desc",
	Lcid = 1033,
	Owner = "admin@tenant.onmicrosoft.com"
};

var newSiteContext = clientContext.CreateSiteAsync(tngci).GetAwaiter().GetResult();
```

**Comment by EagleWizard28** [comment]
Thanks for the feedback @gautamdsheth. It seems as if the  "CreateSiteCollection" returns before everything is correctly provisioned, although I enabled the wait. Since the correct owner isn't assigned then, it is showing "System Account" and hence the setting of the owner with the account that I created the site collection gives the 401 Unauthorized.

I'll give your suggestion a try

**Comment by EagleWizard28** [comment]
@gautamdsheth I tried your proposed solution, which is as also the same method I found in [official documentation](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-provisioning-sites#provision-a-modern-team-site-by-using-the-pnp-csom-core-component).

However it takes **20 minutes** for the site collection to be created. For debugging purposes this is quite a problem. Is it normal for the creation to take that much time and is there a way to accelerate it?

**Comment by gautamdsheth** [comment]
Is it always taking that much time to create a site collection, it could be an anomaly ? At my end, the site creation takes around 4-5 mins. There is no way we can accelerate it as it is happening in the backend. If you have another tenant, could you try there as well ? 

Regarding your main issue about being able to add administrators, was it resolved using this method ?

**Comment by EagleWizard28** [comment]
I've tested to code with 2 different tenants and on both of them it took around 20 minutes. So it is not only my development tenant. I was testing 10 different creations and for those the exception didn't happen, probably because the await in this code is done correctly.

**Comment by EagleWizard28** [comment]
@gautamdsheth seems a change was done in the platform. On my environment creation was cut back to 5 minutes as well, without any code changes. Closing the issue.
