### ISSUE TITLE
Add-SPOPublishingPage

### ISSUE THREAD

**Issue by kameronberget** [SharePoint/PnP-Sites-Core#548]
I am attempting to add a publishing page to my on-premises 2013 site. When trying to run the following command I get an error.

> Add-SPOPublishingPage -PageName "SamplePage.aspx" -PageTemplateName "Blank Web Part page"

**Error:**

```
Add-SPOPublishingPage : pageInformation.PageLayoutListItem
At line:1 char:1
+ Add-SPOPublishingPage -PageName "Test1" -PageTemplateName "Blank Web  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-SPOPublishingPage], ServerException
    + FullyQualifiedErrorId : EXCEPTION,OfficeDevPnP.PowerShell.Commands.AddPublishingPage

```

**Stack Trace:**

```
  at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at Microsoft.SharePoint.Client.PageExtensions.AddPublishingPage(Web web, String pageName, String pageTemplateName, String title, Boolean publish, Folder folder, Nullable`1 startDate, Nullable`1 endDate, Boolean schedule)
   at OfficeDevPnP.PowerShell.Commands.AddPublishingPage.ExecuteCmdlet()
   at OfficeDevPnP.PowerShell.Commands.SPOCmdlet.ProcessRecord()
```

**Comment by erwinvanhunen** [comment]
Did you try with the following?

```
Add-SPOPublishingPage -PageName "SamplePage.aspx" -PageTemplateName "BlankWebPartPage"
```

Notice the difference in spacing. It's not the title but the actual filename (without the extension) of the pagelayout that you need to refer to.

**Comment by PaoloPia** [comment]
Hi,
Have you any feedback about this topic? Or can we close the item? Thanks.

**Comment by jansenbe** [comment]
Internal testing resulted in: "Provisioned publishing pages using Add-SPOPublishingPage command in on-prem and online environments successfully"

Closing issue now.
