### ISSUE TITLE
[PnP-Sites-Core][Bug] NullReferenceException in TokenProviders.ADFS.BaseProvider.TransformSamlTokenToFedAuth

### ISSUE THREAD

**Issue by MateuszTrN** [SharePoint/PnP-Sites-Core#586]
**Category**

[ X] Bug
[ ] Enhancement

**Environment**

[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ X] SharePoint 2013

If SharePoint on-premises, what's exact CU version: September 2015 CU

**Expected or Desired Behavior**

Information what object is null

**Observed Behavior**

Here is the code that I'm using for creating clientContext:

`ClientContext spClientContext = authManager.GetADFSUserNameMixedAuthenticatedContext(url, username, password, domain, sts, idpId);`

Every parameter is passed to the conosle app via command line. 

here I have my Fiddler sshot

![pnp-issue2](https://cloud.githubusercontent.com/assets/4653046/15655653/4bbe23b6-269f-11e6-8bb1-5070a84edba3.PNG)

And finally the code that causes the issue:

```
public void SendRequest(oc_crmsprequests crmSpRequest)
        {
            var sharePointList = _clientContext.Web.Lists.GetByTitle(_listName);

            var itemCreateInfo = new ListItemCreationInformation();
            var listItem = sharePointList.AddItem(itemCreateInfo);
            listItem["Title"] = crmSpRequest.oc_name;

            listItem.Update();

            _clientContext.ExecuteQuery();
        }
```

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
      at OfficeDevPnP.Core.IdentityModel.TokenProviders.ADFS.BaseProvider.TransformSamlTokenToFedAuth(String samlToken, String samlSite, String relyingPartyIdentifier)
   at OfficeDevPnP.Core.IdentityModel.TokenProviders.ADFS.UsernameMixed.GetFedAuthCookie(String siteUrl, String userName, String password, Uri userNameMixed, String relyingPartyIdentifier, Int32 logonTokenCacheExpirationWindow)
   at OfficeDevPnP.Core.AuthenticationManager.<>c__DisplayClass18_0.<GetADFSUserNameMixedAuthenticatedContext>b__0(Object oSender, WebRequestEventArgs webRequestEventArgs)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.OnExecutingWebRequest(WebRequestEventArgs args)
   at Microsoft.SharePoint.Client.ClientContext.FireExecutingWebRequestEventInternal(WebRequestEventArgs args)
   at Microsoft.SharePoint.Client.ClientContext.GetFormDigestInfoPrivate()
   at Microsoft.SharePoint.Client.ClientContext.EnsureFormDigest()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at OC.Temp.OCTempSharepointRequester.SendRequest(oc_crmsprequests crmSpRequest) in c:\Users\Administrator\Source\Repos\OC.CRM - \OC.Temp\OCTempSharepointRequester.cs:line 28

**Comment by MateuszTrN** [comment]
Additional note that I think could be a problem - is it possible that it's happening because we use ADFS 3.0 ?

**Comment by anderzbengtzzon** [comment]
I have the same problem. Using ADFS 3, seems the WrapInSoapMessage function fails as the stsResponse is already a soap message and thus the parsing of the message fails. Is ADFS 3 not supported?

**Comment by jansenbe** [comment]
ADFS 3 was never tested...current implementation would need a complete rewrite using modern auth libraries

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
