### ISSUE TITLE
Provisioning Engine - Unhandled exception on first run if SiteCollection group does not exist

### ISSUE THREAD

**Issue by TVDKoni** [SharePoint/PnP-Sites-Core#616]
PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
[X ] Bug
[X ] Office 365 / SharePoint Online

Working with dev branch:
SHA-1: fc7289c3b81e83ffea741a497fa8188fd40ff692

I try to provision a template to a fresh new created site collection:
Template: http://pastebin.com/6kwzbeJR
Resource: http://pastebin.com/x6tyuxsv

On first run I get following error:
01/05 - Regional Settings
  02/05 - Supported UI Languages
  03/05 - Term Groups
A unhandeled exception occured:
Microsoft.SharePoint.Client.ServerException: Group names must be unique.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay) in C:\Data\Source\github.com\TrivadisCloud\PnP-Sites-Core\Core\OfficeDevPnP.Core\AppModelExtensions\ClientContextExtensions.cs:line 80
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay) in C:\Data\Source\github.com\TrivadisCloud\PnP-Sites-Core\Core\OfficeDevPnP.Core\AppModelExtensions\ClientContextExtensions.cs:line 39
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectTermGroups.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation) in C:\Data\Source\github.com\TrivadisCloud\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectTermGroups.cs:line 72
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo) in C:\Data\Source\github.com\TrivadisCloud\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\SiteToTemplateConversion.cs:line 220
   at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation) in C:\Data\Source\github.com\TrivadisCloud\PnP-Sites-Core\Core\OfficeDevPnP.Core\AppModelExtensions\WebExtensions.cs:line 1082
   at Provisioning.CLI.Console.Program.ApplyTemplate(Parser parser, FileInfo inFile, String tourl) in C:\Data\Source\github.com\TrivadisCloud\PnP\Samples\Provisioning.CLI\Provisioning.CLI.Console\Program.cs:line 315
   at Provisioning.CLI.Console.Program.Main(String[] args) in C:\Data\Source\github.com\TrivadisCloud\PnP\Samples\Provisioning.CLI\Provisioning.CLI.Console\Program.cs:line 154

If I run same template a second time, everything runs well:
  01/05 - Regional Settings
  02/05 - Supported UI Languages
  03/05 - Term Groups
  04/05 - Fields
  05/05 - Content Types
Done

Looks like there is a problem, if the template has to create the site collection term group, if it is referenced in a site field.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. As far as I know this issue should be resolved. Can you confirm? Thanks.

**Comment by PaoloPia** [comment]
See also #617 and #618.

**Comment by jansenbe** [comment]
**Internal testing feedback**: Provisioned user provided template successfully.

Closing issue now
