### ISSUE TITLE
Provisioning Engine - Exception using resources for TermSet name

### ISSUE THREAD

**Issue by TVDKoni** [SharePoint/PnP-Sites-Core#618]
PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
[X ] Bug
[X ] Office 365 / SharePoint Online

Working with dev branch:
SHA-1: fc7289c3b81e83ffea741a497fa8188fd40ff692

Template: http://pastebin.com/vpNfvp0k
Resource: http://pastebin.com/ie7SaANb

I like to use a resource file to specify the TermSet name in different languages. During installation of the template I get an error on a field referencing that TermSet:

  01/05 - Regional Settings
  02/05 - Supported UI Languages
  03/05 - Term Groups
  04/05 - Fields
A unhandeled exception occured:
System.Exception: The field was found invalid:  {termsetid:Site Collection - tenant.sharepoint.com-sites-siteUrl:Trivadis Document Group}
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectField.CreateField(Web web, XElement templateFieldElement, PnPMonitoredScope scope, TokenParser parser, String originalFieldXml) in C:\Data\Source\github.com\TrivadisCloud\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectField.cs:line 242
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectField.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation) in C:\Data\Source\github.com\TrivadisCloud\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectField.cs:line 57
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo) in C:\Data\Source\github.com\TrivadisCloud\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\SiteToTemplateConversion.cs:line 220
   at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation) in C:\Data\Source\github.com\TrivadisCloud\PnP-Sites-Core\Core\OfficeDevPnP.Core\AppModelExtensions\WebExtensions.cs:line 1082
   at Provisioning.CLI.Console.Program.ApplyTemplate(Parser parser, FileInfo inFile, String tourl) in C:\Data\Source\github.com\TrivadisCloud\PnP\Samples\Provisioning.CLI\Provisioning.CLI.Console\Program.cs:line 315
   at Provisioning.CLI.Console.Program.Main(String[] args) in C:\Data\Source\github.com\TrivadisCloud\PnP\Samples\Provisioning.CLI\Provisioning.CLI.Console\Program.cs:line 154

**Comment by nabhendu** [comment]
Hi,
   I am also facing the same issue. Are you able to get the solution?
Thanks,
Nabhendu

**Comment by PaoloPia** [comment]
Same here. This almost the same issue as #616 and #617? I will close this item and keep the original one open. Nevertheless, we have introduced some new tokens to support local Site Collection Term Groups. Thus, I guess this specific issue is now solved. Thanks.
