### ISSUE TITLE
WebJob based Site Provisioning fails intermittently

### ISSUE THREAD

**Issue by jpalo** [SharePoint/PnP-Sites-Core#964]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online

#### Expected or Desired Behavior
Site provisioning would work coherently without issues. We're using the model based on sample https://github.com/SharePoint/PnP/tree/master/Samples/Provisioning.Cloud.Async.WebJob.

#### Observed Behavior
Some days site provisioning works, some days not. One day, site provisioning (ctx.Web.ApplyProvisioningTemplate) might fail in site provisioning step _Applying template: Phase 07/12 - List instances_ with
```
1/11/2017 8:12:08 AM Applying template: Phase 07/12 - List instances
1/11/2017 8:16:10 AM Site collection creation to URL Prozessmanagement failed with following details.
Microsoft.SharePoint.Client.ServerException: Column 'VideoSetUserOverrideEncoding' does not exist. It may have been deleted by another user.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at Microsoft.SharePoint.Client.ClientObjectExtensions.EnsureProperties[T](T clientObject, Expression`1[] propertySelector)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.CreateView(Web web, View view, ViewCollection existingViews, List createdList, PnPMonitoredScope monitoredScope, TokenParser parser)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo)
   at XYZ.YXZ.Cloud.Async.Common.SiteManager.ApplyCustomTemplateToSite(ClientContext ctx, SiteCollectionRequest siteRequest, String resourcesPath, TextWriter log)
   at XYZ.YXZ.Cloud.Async.Job.Functions.ProcessQueueMessage(SiteCollectionRequest siteRequest, TextWriter log)
Exception while executing function: Functions.ProcessQueueMessage
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.ProcessQueueMessage ---> Microsoft.SharePoint.Client.ServerException: Column 'VideoSetUserOverrideEncoding' does not exist. It may have been deleted by another user.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at Microsoft.SharePoint.Client.ClientObjectExtensions.EnsureProperties[T](T clientObject, Expression`1[] propertySelector)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.CreateView(Web web, View view, ViewCollection existingViews, List createdList, PnPMonitoredScope monitoredScope, TokenParser parser)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo)
   at XYZ.YXZ.Cloud.Async.Common.SiteManager.ApplyCustomTemplateToSite(ClientContext ctx, SiteCollectionRequest siteRequest, String resourcesPath, TextWriter log)
   at XYZ.YXZ.Cloud.Async.Job.Functions.ProcessQueueMessage(SiteCollectionRequest siteRequest, TextWriter log)
   at lambda_method(Closure , Functions , Object[] )
   at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`1.InvokeAsync(TReflected instance, Object[] arguments)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.<InvokeAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__2c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
   --- End of inner exception stack trace ---
```

or at _Applying template: Phase 12/12 - Navigation_ with 

```
1/11/2017 8:58:50 AM Site collection creation to URL test1101 failed with following details.
Microsoft.SharePoint.Client.ServerException: Cannot open "/teams/test1101/Pages/PageNotFoundError.aspx": no such file or folder.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at Microsoft.SharePoint.Client.NavigationExtensions.AddNavigationNode(Web web, String nodeTitle, Uri nodeUri, String parentNodeTitle, NavigationType navigationType, Boolean isExternal, Boolean asLastNode)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectNavigation.ProvisionStructuralNavigationNodes(Web web, TokenParser parser, NavigationType navigationType, NavigationNodeCollection nodes, PnPMonitoredScope scope, String parentNodeTitle)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectNavigation.ProvisionStructuralNavigation(Web web, StructuralNavigation structuralNavigation, TokenParser parser, Boolean currentNavigation, PnPMonitoredScope scope)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectNavigation.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo)
   at XYZ.YXZ.Cloud.Async.Common.SiteManager.ApplyCustomTemplateToSite(ClientContext ctx, SiteCollectionRequest siteRequest, String resourcesPath, TextWriter log)
   at XYZ.YXZ.Cloud.Async.Job.Functions.ProcessQueueMessage(SiteCollectionRequest siteRequest, TextWriter log)
Exception while executing function: Functions.ProcessQueueMessage
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.ProcessQueueMessage ---> Microsoft.SharePoint.Client.ServerException: Cannot open "/teams/test1101/Pages/PageNotFoundError.aspx": no such file or folder.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at Microsoft.SharePoint.Client.NavigationExtensions.AddNavigationNode(Web web, String nodeTitle, Uri nodeUri, String parentNodeTitle, NavigationType navigationType, Boolean isExternal, Boolean asLastNode)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectNavigation.ProvisionStructuralNavigationNodes(Web web, TokenParser parser, NavigationType navigationType, NavigationNodeCollection nodes, PnPMonitoredScope scope, String parentNodeTitle)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectNavigation.ProvisionStructuralNavigation(Web web, StructuralNavigation structuralNavigation, TokenParser parser, Boolean currentNavigation, PnPMonitoredScope scope)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectNavigation.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo)
   at XYZ.YXZ.Cloud.Async.Common.SiteManager.ApplyCustomTemplateToSite(ClientContext ctx, SiteCollectionRequest siteRequest, String resourcesPath, TextWriter log)
   at XYZ.YXZ.Cloud.Async.Job.Functions.ProcessQueueMessage(SiteCollectionRequest siteRequest, TextWriter log)
   at lambda_method(Closure , Functions , Object[] )
   at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`1.InvokeAsync(TReflected instance, Object[] arguments)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.<InvokeAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__2c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
   --- End of inner exception stack trace ---
```

Sometimes it just times out for few hours, then recovers and starts to work

```
1/11/2017 7:22:18 AM Retrieving custom template from https://XYZ.sharepoint.com/sites/strictlyconfidential...
1/11/2017 7:29:07 AM Site collection creation to URL ProjectImprovementmanagement failed with following details.
System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.GetRequestStream()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at Microsoft.SharePoint.Client.ClientObjectExtensions.EnsureProperty[T,TResult](T clientObject, Expression`1 propertySelector)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectPublishing.GetFiles(Folder folder)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectPublishing.GetFiles(Folder folder)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectPublishing.GetFiles(Folder folder)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectPublishing.ExtractMasterPagesAndPageLayouts(Web web, ProvisioningTemplate template, PnPMonitoredScope scope, ProvisioningTemplateCreationInformation creationInfo)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectPublishing.ExtractObjects(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
   at XYZ.YXZ.Cloud.Async.Common.SiteManager.ApplyCustomTemplateToSite(ClientContext ctx, SiteCollectionRequest siteRequest, String resourcesPath, TextWriter log)
   at XYZ.YXZ.Cloud.Async.Job.Functions.ProcessQueueMessage(SiteCollectionRequest siteRequest, TextWriter log)
Exception while executing function: Functions.ProcessQueueMessage
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.ProcessQueueMessage ---> System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.GetRequestStream()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at Microsoft.SharePoint.Client.ClientObjectExtensions.EnsureProperty[T,TResult](T clientObject, Expression`1 propertySelector)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectPublishing.GetFiles(Folder folder)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectPublishing.GetFiles(Folder folder)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectPublishing.GetFiles(Folder folder)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectPublishing.ExtractMasterPagesAndPageLayouts(Web web, ProvisioningTemplate template, PnPMonitoredScope scope, ProvisioningTemplateCreationInformation creationInfo)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectPublishing.ExtractObjects(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
   at XYZ.YXZ.Cloud.Async.Common.SiteManager.ApplyCustomTemplateToSite(ClientContext ctx, SiteCollectionRequest siteRequest, String resourcesPath, TextWriter log)
   at XYZ.YXZ.Cloud.Async.Job.Functions.ProcessQueueMessage(SiteCollectionRequest siteRequest, TextWriter log)
   at lambda_method(Closure , Functions , Object[] )
   at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`1.InvokeAsync(TReflected instance, Object[] arguments)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.<InvokeAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__2c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
   --- End of inner exception stack trace ---
``` 

The next day (or after few hours) all is good without any action on our behalf. In all scenarios the source site template is the same and hasn't been modified. E.g., right now site provisioning again works, but looking at logs from yesterday, there have been errors such as above. Using the latest PnP from NuGet. 

I have a feeling the ever-updating SPO causes the issues and unsure if there's even anything in PnP that could be done to minimize these downtimes in Site Provisioning. Would using custom provisioning XML instead of actual template site offer any improvement?

#### Steps to Reproduce
So far I haven't found any ways to reproduce the issue. It occurs every now and then, lasts few hours or longer, then recovers.

**Comment by KEMiCZA** [comment]
Are you disposing all your ClientContext objects?

**Comment by erwinvanhunen** [comment]
Hi Jussi,

None if the issues you report here seem directly related to the provisioning engine as such or it's XML schema, as the errors all seem to occur on CSOM API level. Yes, O365 is evergreen, however, that is on a low level, not on the structure of a site. If a site has a structure, it has that structure. E.g. if a page is available, it will be available, e.g. MS will not delete a page. However, if a template was extracted from a template site, and in the meantime the site definition (e.g. the 'server side template') changes for that site (usually STS#0) then of course there -can- be differences between the extracted template and the newly created site. We however updated or 'internal' knowledge about the templates on a monthly basis. E.g. the engine is updated with information about the templates out there on a monthly basis.

If the code is creating both the sitecollection -and- applying the template in one go you could very well run into timeout issues given the time it takes to create site collection in O365. 

With the risk of telling you nothing new:
A webjob times out based upon CPU and output. E.g. if the job does not generate output (like a heartbeat message like '.') the job can timeout and the process will break. Do you use your own code to create the site collection? If so, have the timerjob generate output to the log. Otherwise, if you use the latest release of PnP Core, you can add a timeout function to the method that will be called at certain polling intervals. In there you can create output during the webjob. The code you use is as follows:

```csharp
Tenant.CreateSiteCollection(mySiteentity, timeoutFunction: (operationmessage) =>
{
    if (operationmessage == TenantOperationMessage.CreatingSiteCollection)
    {
        Console.Write("."); // heartbeat
    }
    return false; // set to true to cancel the wait loop
});
```

What would be interesting to know is that if you run the code from the webjob from your local machine, do you experience the same issues? If not, it's related to the Azure WebJobs you're running. OR you tenant.

**Comment by jansenbe** [comment]
Closing this issue since we've not received feedback for a long time. We want to further investigate this, but if there's no feedback we can't. Absolutely fine for you to re-open the issue if you can still re-produce using the March 2017 release or if you have additional context that can help.

**Comment by jpalo** [comment]
One of the more common errors we're currently seeing across tenants is timeout when SiteManager.cs is getting template at 

```
// Get template from existing site
template = cc2.Web.GetProvisioningTemplate(creationInfo);
```

and it doesn't support timeoutFunction. Any chance of adding that? What puzzles me is that the timeouts occur at around 3-5 minutes, which is quite short and not consistent, so I'm not sure if that falls into something that can be solved using heartbeat. Runtime from the very beginning until these timeouts is around 10-13 min so I'm having hard time figuring out what timeout value could affect this (if any).

One of the latest timeout error messages, which is prety interesting as there is clearly some internal retry operation going on at the bottom (ThrowForNonSuccess).

```
3/24/2017 7:33:40 AM Retrieving custom template from https://company.sharepoint.com/sites/strictlyconfidential...
3/24/2017 7:37:25 AM Site collection creation to URL atest-2401-4 failed with following details.
System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.GetRequestStream()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectSiteSecurity.ExtractObjects(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
   at company.xyz.Cloud.Async.Common.SiteManager.ApplyCustomTemplateToSite(ClientContext ctx, SiteCollectionRequest siteRequest, String resourcesPath, TextWriter log)
   at company.xyz.Cloud.Async.Job.Functions.ProcessQueueMessage(SiteCollectionRequest siteRequest, TextWriter log)
Exception while executing function: Functions.ProcessQueueMessage
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.ProcessQueueMessage ---> System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.GetRequestStream()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectSiteSecurity.ExtractObjects(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
   at company.xyz.Cloud.Async.Common.SiteManager.ApplyCustomTemplateToSite(ClientContext ctx, SiteCollectionRequest siteRequest, String resourcesPath, TextWriter log)
   at company.xyz.Cloud.Async.Job.Functions.ProcessQueueMessage(SiteCollectionRequest siteRequest, TextWriter log)
   at lambda_method(Closure , Functions , Object[] )
   at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`1.InvokeAsync(TReflected instance, Object[] arguments)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.<InvokeAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<InvokeAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
   --- End of inner exception stack trace ---
```
