### ISSUE TITLE
Provisioning of Site Collection fails: Operation is not valid due to the current state of the object

### ISSUE THREAD

**Issue by Enghaug** [SharePoint/PnP-Sites-Core#984]
Provisioning of Site Collections fails with this exception message "Operation is not valid due to the current state of the object". This is happening occasionally, but has been more frequent during the last month.  

It looks like the exception is thrown inside the pnp extension method for the tenant object called "GetSiteGuidByUrl". Any ideas what cause this issue?

```
Exception occurred: Operation is not valid due to the current state of the object.

Stack Trace:
at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
at Microsoft.SharePoint.Client.TenantExtensions.GetSiteGuidByUrl(Tenant tenant, Uri siteFullUrl)
at Microsoft.SharePoint.Client.TenantExtensions.CreateSiteCollection(Tenant tenant, SiteEntity properties, Boolean removeFromRecycleBin, Boolean wait)
at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.SiteCollectionProvisioningJobHandler.CreateSiteCollection(SiteCollectionProvisioningJob job)
at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.SiteCollectionProvisioningJobHandler.RunJobInternal(ProvisioningJob job)
at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.ProvisioningJobHandler.RunJob(ProvisioningJob job)```

**Comment by VesaJuvonen** [comment]
Hi Enghaug, this is unfortunately an issue in native CSOM server side. When you have created a site collection using app-only, you might right into this issue with Tenant object. Latest Core and PowerShell versions have been adjusted to "eat up the exception" when this happens. Root issue will be fixed by our SP engineering sooner or later.
